// ==========================================
// 1. VOCABULARY BASE DATA (N4: Lessons 26-50)
// ==========================================
const rawCards = [
    // Lesson 26 Data[span_0](start_span)[span_0](end_span)
    { kanji: "見ます、診ます", kana: "みます", bn: "দেখা, চেক করা", lesson: 26 },
    { kanji: "探します、捜します", kana: "さがします", bn: "খোঁজা, অনুসন্ধান করা", lesson: 26 },
    { kanji: "遅れます [時間に～]", kana: "おくれます [じかんに～]", bn: "দেরি করা [সময় ]", lesson: 26 },
    { kanji: "間に合います [時間に～]", kana: "まにあいます [じかんに～]", bn: "সময় মত পৌঁছানো", lesson: 26 },
    { kanji: "やります", kana: "やります", bn: "করা", lesson: 26 },
    { kanji: "拾います", kana: "ひろいます", bn: "তুলে নেওয়া, আরোগ্য", lesson: 26 },
    { kanji: "連絡します", kana: "れんらくします", bn: "যোগাযোগ করা", lesson: 26 },
    { kanji: "気分がいい", kana: "きぶんがいい", bn: "ভালো অনুভব করা", lesson: 26 },
    { kanji: "気分が悪い", kana: "きぶんがわるい", bn: "খারাপ অনুভব করা", lesson: 26 },
    { kanji: "運動会", kana: "うんどうかい", bn: "ক্রীড়া দিবস", lesson: 26 },
    { kanji: "ぼんおどり", kana: "ぼんおどり", bn: "বন উৎসবের নাচ", lesson: 26 },
    { kanji: "フリーマーケット", kana: "フリーマーケット", bn: "সস্তা বাজার", lesson: 26 },
    { kanji: "場所", kana: "ばしょ", bn: "জায়গা", lesson: 26 },
    { kanji: "ボランティア", kana: "ボランティア", bn: "ভলান্টিয়ার, স্বেচ্ছাসেবক", lesson: 26 },
    { kanji: "財布", kana: "さいふ", bn: "মানিব্যাগ", lesson: 26 },
    { kanji: "ごみ", kana: "ごみ", bn: "বর্জ্য, ময়লা", lesson: 26 },
    { kanji: "国会議事堂", kana: "こっかいぎじどう", bn: "ডায়েট বিল্ডিং", lesson: 26 },
    { kanji: "平日", kana: "へいじつ", bn: "সাপ্তাহিক ছুটি", lesson: 26 },
    { kanji: "～弁", kana: "～べん", bn: "~ উপভাষা", lesson: 26 },
    { kanji: "今度", kana: "こんど", bn: "অন্যসময়, পরের বার", lesson: 26 },
    { kanji: "ずいぶん", kana: "ずいぶん", bn: "খুব, সুন্দর", lesson: 26 },
    { kanji: "直接", kana: "ちょくせつ", bn: "সরাসরি", lesson: 26 },
    { kanji: "いつでも", kana: "いつでも", bn: "যেকোন সময়", lesson: 26 },
    { kanji: "どこでも", kana: "どこでも", bn: "যেকোন জায়গা", lesson: 26 },
    { kanji: "だれでも", kana: "だれでも", bn: "যে কেউ", lesson: 26 },
    { kanji: "何でも", kana: "なんでも", bn: "যেকোন কিছু", lesson: 26 },
    { kanji: "こんな ～", kana: "こんな ～", bn: "~ এটার মত", lesson: 26 },
    { kanji: "そんな ～", kana: "そんな ～", bn: "~ ওটার মত", lesson: 26 },
    { kanji: "あんな ～", kana: "あんな ～", bn: "~ ঐটার মত", lesson: 26 },
    { kanji: "片付きます [荷物が～]", kana: "かたづきます [にもつが～]", bn: "গুছানো, সাজানো [জিনিসপত্র]", lesson: 26 },
    { kanji: "出します [ごみを～]", kana: "だします [ごみを～]", bn: "বাইরে বের করা [ময়লা]", lesson: 26 },
    { kanji: "置き場", kana: "おきば", bn: "কিছু রাখার জায়গা", lesson: 26 },
    { kanji: "燃えるごみ", kana: "もえるごみ", bn: "পোড়া ময়লা", lesson: 26 },
    { kanji: "横", kana: "よこ", bn: "সাইড", lesson: 26 },
    { kanji: "瓶", kana: "びん", bn: "বোতল", lesson: 26 },
    { kanji: "缶", kana: "かん", bn: "ক্যান", lesson: 26 },
    { kanji: "ガス", kana: "ガス", bn: "গ্যাস", lesson: 26 },
    { kanji: "～会社", kana: "～がいしゃ", bn: "~ কোম্পানি", lesson: 26 },
    { kanji: "宇宙", kana: "うちゅう", bn: "মহাকাশ", lesson: 26 },
    { kanji: "～様", kana: "～さま", bn: "~ জনাব/বেগম", lesson: 26 },
    { kanji: "宇宙船", kana: "うちゅうせん", bn: "মহাকাশযান", lesson: 26 },
    { kanji: "怖い", kana: "こわい", bn: "ভয়", lesson: 26 },
    { kanji: "ステーション", kana: "ステーション", bn: "স্টেশন", lesson: 26 },
    { kanji: "違います", kana: "ちがいます", bn: "অন্যরকম", lesson: 26 },
    { kanji: "宇宙飛行士", kana: "うちゅうひこうし", bn: "নভোচারী", lesson: 26 },
    { kanji: "参加します", kana: "さんかします", bn: "অংশ নেওয়া", lesson: 26 },
    { kanji: "申し込みます", kana: "もうしこみます", bn: "আবেদন করা, ভর্তি ফর্ম", lesson: 26 },
    { kanji: "都合がいい", kana: "つごうがいい", bn: "সুবিধাজনক সময়", lesson: 26 },
    { kanji: "都合が悪い", kana: "つごうがわるい", bn: "অসুবিধাজনক সময়", lesson: 26 },
    { kanji: "新聞社", kana: "しんぶんしゃ", bn: "পত্রিকা কোম্পানি", lesson: 26 },
    { kanji: "柔道", kana: "じゅうどう", bn: "জুডো", lesson: 26 },
    { kanji: "子供の日", kana: "こどものひ", bn: "শিশু দিবস", lesson: 26 },
    { kanji: "月水金", kana: "げつすいきん", bn: "সোম বুধ শুক্র", lesson: 26 },
    { kanji: "お湯", kana: "おゆ", bn: "গরম পানি", lesson: 26 },
    { kanji: "困ったなあ", kana: "こまったなあ", bn: "আমি কি করবো? শান্তিতে", lesson: 26 },
    { kanji: "電子メール", kana: "でんしメール", bn: "ইলেকট্রনিক মেইল", lesson: 26 },
    { kanji: "別の", kana: "べつの", bn: "আলাদা, অন্য", lesson: 26 },
    { kanji: "星出明彦", kana: "ほしであきひこ", bn: "হোশিদেআকিহিকো (জাপানি নভোচারী (১৯৬৮-))", lesson: 26 },
    { kanji: "エドヤストア", kana: "エドヤストア", bn: "এডোইয়াস্টোর", lesson: 26 },

    // Lesson 27 Data[span_1](start_span)[span_1](end_span)
    { kanji: "飼います", kana: "かいます", bn: "রাখা (পোষা প্রাণী), পালন করা (প্রাণী)", lesson: 27 },
    { kanji: "走ります [道を～]", kana: "はしります [みちを～]", bn: "চালানো, ড্রাইভ করা [রাস্তায়]", lesson: 27 },
    { kanji: "見えます [山が～]", kana: "みえます [やまが～]", bn: "দেখতে পারা [পর্বত]", lesson: 27 },
    { kanji: "聞こえます [音が～]", kana: "きこえます [おとが～]", bn: "শুনতে পারা [শব্দ]", lesson: 27 },
    { kanji: "できます [道が～]", kana: "できます [みちが～]", bn: "তৈরি করা, সমাপ্ত হওয়া [রাস্তা]", lesson: 27 },
    { kanji: "開きます [教室を～]", kana: "ひらきます [きょうしつを～]", bn: "তৈরি করা [ক্লাস], খোলা, চালু করা", lesson: 27 },
    { kanji: "心配 [な]", kana: "しんぱい [な]", bn: "দুশ্চিন্তা, উদ্বিগ্ন", lesson: 27 },
    { kanji: "ペット", kana: "ペット", bn: "পোষা, পোষ্য", lesson: 27 },
    { kanji: "鳥", kana: "とり", bn: "পাখি", lesson: 27 },
    { kanji: "声", kana: "こえ", bn: "কণ্ঠস্বর", lesson: 27 },
    { kanji: "波", kana: "なみ", bn: "ঢেউ", lesson: 27 },
    { kanji: "花火", kana: "はなび", bn: "আতশবাজি", lesson: 27 },
    { kanji: "道具", kana: "どうぐ", bn: "যন্ত্রপাতি, সরঞ্জাম", lesson: 27 },
    { kanji: "クリーニング", kana: "クリーニング", bn: "লন্ড্রি, পরিষ্কার", lesson: 27 },
    { kanji: "家", kana: "いえ", bn: "বাড়ি", lesson: 27 },
    { kanji: "マンション", kana: "マンション", bn: "বাসাবাড়ি, ফ্ল্যাট", lesson: 27 },
    { kanji: "キッチン", kana: "キッチン", bn: "রান্নাঘর", lesson: 27 },
    { kanji: "～教室", kana: "～きょうしつ", bn: "শ্রেণিকক্ষ", lesson: 27 },
    { kanji: "パーティールーム", kana: "パーティールーム", bn: "পার্টিরুম", lesson: 27 },
    { kanji: "方", kana: "かた", bn: "ব্যক্তি", lesson: 27 },
    { kanji: "～後", kana: "～ご", bn: "পরে ~", lesson: 27 },
    { kanji: "～しか", kana: "～しか", bn: "শুধু ~", lesson: 27 },
    { kanji: "ほかの", kana: "ほかの", bn: "এছাড়াও, পাশাপাশি", lesson: 27 },
    { kanji: "はっきり", kana: "はっきり", bn: "পরিষ্কার, স্পষ্ট", lesson: 27 },
    { kanji: "休みを取ります", kana: "やすみをとります", bn: "ছুটি নেয়া", lesson: 27 },
    { kanji: "漫画", kana: "まんが", bn: "কার্টুন", lesson: 27 },
    { kanji: "ロボット", kana: "ロボット", bn: "রোবট", lesson: 27 },
    { kanji: "家具", kana: "かぐ", bn: "আসবাবপত্র", lesson: 27 },
    { kanji: "本棚", kana: "ほんだな", bn: "বইয়ের তাক", lesson: 27 },
    { kanji: "いつか", kana: "いつか", bn: "একদিন, কিছু দিন", lesson: 27 },
    { kanji: "建てます", kana: "たてます", bn: "নির্মাণ করা", lesson: 27 },
    { kanji: "すばらしい", kana: "すばらしい", bn: "চমৎকার", lesson: 27 },
    { kanji: "子供たち", kana: "こどもたち", bn: "বাচ্চারা", lesson: 27 },
    { kanji: "大好き [な]", kana: "だいすき [な]", bn: "খুব পছন্দ করা", lesson: 27 },
    { kanji: "主人公", kana: "しゅじんこう", bn: "নায়ক, নায়িকা", lesson: 27 },
    { kanji: "形", kana: "かたち", bn: "আকার, আকৃতি", lesson: 27 },
    { kanji: "不思議 [な]", kana: "ふしぎ [な]", bn: "রহস্যময়, দুর্দান্ত", lesson: 27 },
    { kanji: "ポケット", kana: "ポケット", bn: "পকেট", lesson: 27 },
    { kanji: "例えば", kana: "たとえば", bn: "উদাহরণস্বরূপ", lesson: 27 },
    { kanji: "付けます", kana: "つけます", bn: "সংযুক্ত করা, চালু করা", lesson: 27 },
    { kanji: "自由に", kana: "じゆうに", bn: "স্বাধীনভাবে", lesson: 27 },
    { kanji: "空", kana: "そら", bn: "আকাশ", lesson: 27 },
    { kanji: "飛びます", kana: "とびます", bn: "উড়া", lesson: 27 },
    { kanji: "昔", kana: "むかし", bn: "প্রাচীনকাল, পুরোনো দিন", lesson: 27 },
    { kanji: "自分", kana: "じぶん", bn: "নিজের", lesson: 27 },
    { kanji: "将来", kana: "しょうらい", bn: "ভবিষ্যৎ", lesson: 27 },
    { kanji: "景色", kana: "けしき", bn: "দৃশ্য", lesson: 27 },
    { kanji: "昼間", kana: "ひるま", bn: "দিনের সময়", lesson: 27 },
    { kanji: "自動販売機", kana: "じどうはんばいき", bn: "ভেন্ডিং মেশিন", lesson: 27 },
    { kanji: "通信販売", kana: "つうしんはんばい", bn: "ডাকযোগে", lesson: 27 },
    { kanji: "ほとんど", kana: "ほとんど", bn: "প্রায় সব (হ্যাঁ বোধক), খুবই কম (না বোধক)", lesson: 27 },
    { kanji: "関西空港", kana: "かんさいくうこう", bn: "কানসাই বিমানবন্দর", lesson: 27 },
    { kanji: "秋葉原", kana: "あきはばら", bn: "অনেক ইলেকট্রিক ও ইলেকট্রিক্যাল দোকানের শপিং জেলা", lesson: 27 },
    { kanji: "伊豆", kana: "いず", bn: "উপদ্বীপ শিজুকা প্রদেশের", lesson: 27 },
    { kanji: "日曜大工", kana: "にちようだいく", bn: "রবিবারের ছুতোর", lesson: 27 },
    { kanji: "夢", kana: "ゆめ", bn: "স্বপ্ন", lesson: 27 },
    { kanji: "夢を見ます", kana: "ゆめをみます", bn: "স্বপ্ন দেখা", lesson: 27 },
    { kanji: "ドラえもん", kana: "ドラえもん", bn: "ডোরেমন", lesson: 27 },

    // Lesson 28 Data[span_2](start_span)[span_2](end_span)
    { kanji: "売れます [パンが～]", kana: "うれます [パンが～]", bn: "বিক্রি করা [রুটি]", lesson: 28 },
    { kanji: "踊ります", kana: "おどります", bn: "নাচ", lesson: 28 },
    { kanji: "かみます", kana: "かみます", bn: "চিবানো, কামড়", lesson: 28 },
    { kanji: "選びます", kana: "えらびます", bn: "পছন্দ", lesson: 28 },
    { kanji: "通います [大学に～]", kana: "かよいます [だいがくに～]", bn: "যাওয়া আসা [বিশ্ববিদ্যালয়ে]", lesson: 28 },
    { kanji: "メモします", kana: "メモします", bn: "মেমো করা", lesson: 28 },
    { kanji: "まじめ [な]", kana: "まじめ [な]", bn: "সিরিয়াস", lesson: 28 },
    { kanji: "熱心 [な]", kana: "ねっしん [な]", bn: "আন্তরিক, উদ্যমী", lesson: 28 },
    { kanji: "偉い", kana: "えらい", bn: "মহৎ, প্রশংসনীয়", lesson: 28 },
    { kanji: "ちょうどいい", kana: "ちょうどいい", bn: "যথাযথ, ঠিক", lesson: 28 },
    { kanji: "景色", kana: "けしき", bn: "দৃশ্য, দেখা", lesson: 28 },
    { kanji: "美容院", kana: "びよういん", bn: "চুল কাটার সেলুন", lesson: 28 },
    { kanji: "台所", kana: "だいどころ", bn: "রান্নাঘর", lesson: 28 },
    { kanji: "経験", kana: "けいけん", bn: "অভিজ্ঞতা", lesson: 28 },
    { kanji: "力", kana: "ちから", bn: "শক্তি", lesson: 28 },
    { kanji: "人気", kana: "にんき", bn: "জনপ্রিয়তা", lesson: 28 },
    { kanji: "形", kana: "かたち", bn: "আকৃতি, আকার", lesson: 28 },
    { kanji: "色", kana: "いろ", bn: "রং", lesson: 28 },
    { kanji: "味", kana: "あじ", bn: "স্বাদ", lesson: 28 },
    { kanji: "ガム", kana: "ガム", bn: "চুইংগাম", lesson: 28 },
    { kanji: "品物", kana: "しなもの", bn: "পণ্য", lesson: 28 },
    { kanji: "値段", kana: "ねだん", bn: "দাম", lesson: 28 },
    { kanji: "給料", kana: "きゅうりょう", bn: "বেতন", lesson: 28 },
    { kanji: "ボーナス", kana: "ボーナス", bn: "বোনাস", lesson: 28 },
    { kanji: "ゲーム", kana: "ゲーム", bn: "কম্পিউটার গেম", lesson: 28 },
    { kanji: "番組", kana: "ばんぐみ", bn: "প্রোগ্রাম", lesson: 28 },
    { kanji: "ドラマ", kana: "ドラマ", bn: "নাটক", lesson: 28 },
    { kanji: "歌手", kana: "かしゅ", bn: "গায়ক, শিল্পী", lesson: 28 },
    { kanji: "小説", kana: "しょうせつ", bn: "উপন্যাস", lesson: 28 },
    { kanji: "小説家", kana: "しょうせつか", bn: "ঔপন্যাসিক", lesson: 28 },
    { kanji: "～家", kana: "～か", bn: "এইগুলো শব্দের শেষে বসে", lesson: 28 },
    { kanji: "～機", kana: "～き", bn: "~যন্ত্র", lesson: 28 },
    { kanji: "息子", kana: "むすこ", bn: "আমার ছেলে", lesson: 28 },
    { kanji: "息子さん", kana: "むすこさん", bn: "অন্যের ছেলে", lesson: 28 },
    { kanji: "娘", kana: "むすめ", bn: "আমার মেয়ে", lesson: 28 },
    { kanji: "娘さん", kana: "むすめさん", bn: "অন্যের মেয়ে", lesson: 28 },
    { kanji: "自分", kana: "じぶん", bn: "নিজের", lesson: 28 },
    { kanji: "将来", kana: "しょうらい", bn: "ভবিষ্যৎ", lesson: 28 },
    { kanji: "しばらく", kana: "しばらく", bn: "কিছুক্ষণ", lesson: 28 },
    { kanji: "たいてい", kana: "たいてい", bn: "সাধারণত, অধিকাংশ", lesson: 28 },
    { kanji: "それに", kana: "それに", bn: "তাছাড়াও", lesson: 28 },
    { kanji: "それで", kana: "それで", bn: "এবং তাই", lesson: 28 },
    { kanji: "ちょっとお願いがあるんですが。", kana: "ちょっとおねがいがあるんですが。", bn: "আমার ছোট একটা আবদার আছে।", lesson: 28 },
    { kanji: "実は", kana: "じつは", bn: "মূলত, সত্য কথা বলতে", lesson: 28 },
    { kanji: "会話", kana: "かいわ", bn: "কথোপকথন", lesson: 28 },
    { kanji: "うーん", kana: "うーん", bn: "ভালো, আমাকে দেখতে দাও, হুমম.....", lesson: 28 },
    { kanji: "お知らせ", kana: "おしらせ", bn: "বিজ্ঞপ্তি", lesson: 28 },
    { kanji: "参加します", kana: "さんかします", bn: "অংশগ্রহন করা, যোগ দেয়া", lesson: 28 },
    { kanji: "日にち", kana: "ひにち", bn: "তারিখ", lesson: 28 },
    { kanji: "土", kana: "ど", bn: "শনিবার", lesson: 28 },
    { kanji: "体育館", kana: "たいいくかん", bn: "জিমনেশিয়াম", lesson: 28 },
    { kanji: "無料", kana: "むりょう", bn: "খরচ ছাড়া", lesson: 28 },
    { kanji: "誘います", kana: "さそいます", bn: "দাওয়াত, কাউকে যোগ দিতে বলা", lesson: 28 },
    { kanji: "イベント", kana: "イベント", bn: "ইভেন্ট", lesson: 28 },

    // Lesson 29 Data[span_3](start_span)[span_3](end_span)
    { kanji: "開きます [ドアが～]", kana: "あきます [ドアが～]", bn: "খোলা [দরজা]", lesson: 29 },
    { kanji: "閉まります [ドアが～]", kana: "しまります [ドアが～]", bn: "বন্ধ করা [দরজা]", lesson: 29 },
    { kanji: "つきます [電気が～]", kana: "つきます [でんきが～]", bn: "চালু করা, অন করা [লাইট]", lesson: 29 },
    { kanji: "消えます [電気が～]", kana: "きえます [でんきが～]", bn: "বন্ধ করা [লাইট]", lesson: 29 },
    { kanji: "壊れます [いすが～]", kana: "こわれます [いすが～]", bn: "ভাঙ্গা [চেয়ার]", lesson: 29 },
    { kanji: "割れます [コップが～]", kana: "われます [コップが～]", bn: "ভাঙ্গা [গ্লাস, কাপ]", lesson: 29 },
    { kanji: "折れます [木が～]", kana: "おれます [きが～]", bn: "ভাঙ্গা [গাছ]", lesson: 29 },
    { kanji: "破れます [紙が～]", kana: "やぶれます [かみが～]", bn: "ছেঁড়া, বিচ্ছিন্ন করা [কাগজ]", lesson: 29 },
    { kanji: "汚れます [服が～]", kana: "よごれます [ふくが～]", bn: "ময়লা করা [পোশাক]", lesson: 29 },
    { kanji: "付きます [ポケットが～]", kana: "つきます [ポケットが～]", bn: "লাগানো [পকেট]", lesson: 29 },
    { kanji: "外れます [ボタンが～]", kana: "はずれます [ボタンが～]", bn: "খুলে পড়া [বোতাম]", lesson: 29 },
    { kanji: "止まります [車が～]", kana: "とまります [くるまが～]", bn: "থামানো, দাঁড় করানো [গাড়ি]", lesson: 29 },
    { kanji: "間違えます", kana: "まちがえます", bn: "ভুল করা", lesson: 29 },
    { kanji: "落とします", kana: "おとします", bn: "হারিয়ে যাওয়া, পড়ে যাওয়া", lesson: 29 },
    { kanji: "掛かります [かぎが～]", kana: "かかります [かぎが～]", bn: "তালা লাগানো", lesson: 29 },
    { kanji: "拭きます", kana: "ふきます", bn: "মুছা", lesson: 29 },
    { kanji: "取り替えます", kana: "とりかえます", bn: "পরিবর্তন করা", lesson: 29 },
    { kanji: "片付けます", kana: "かたづけます", bn: "গোছানো, সাজানো", lesson: 29 },
    { kanji: "お皿", kana: "おさら", bn: "প্লেট, ডিশ", lesson: 29 },
    { kanji: "お茶碗", kana: "おちゃわん", bn: "ভাতের বোল বা বাটি", lesson: 29 },
    { kanji: "コップ", kana: "コップ", bn: "কাপ", lesson: 29 },
    { kanji: "ガラス", kana: "ガラス", bn: "গ্লাস", lesson: 29 },
    { kanji: "袋", kana: "ふくろ", bn: "ব্যাগ, থলে", lesson: 29 },
    { kanji: "書類", kana: "しょるい", bn: "ডকুমেন্ট, কাগজপত্র", lesson: 29 },
    { kanji: "枝", kana: "えだ", bn: "শাখা, ব্রাঞ্চ", lesson: 29 },
    { kanji: "駅員", kana: "えきいん", bn: "স্টেশন কর্মী", lesson: 29 },
    { kanji: "交番", kana: "こうばん", bn: "পুলিশ বক্স", lesson: 29 },
    { kanji: "スピーチ", kana: "スピーチ", bn: "বক্তৃতা", lesson: 29 },
    { kanji: "返事", kana: "へんじ", bn: "উত্তর দেয়া", lesson: 29 },
    { kanji: "お先に どうぞ", kana: "おさきに どうぞ", bn: "আপনার পরে / সামনে যান, প্লিজ", lesson: 29 },
    { kanji: "源氏物語", kana: "げんじものがたり", bn: "হেইয়ান যুগে মুরাসাকি শিকিবুর লেখা একটি উপন্যাস", lesson: 29 },
    { kanji: "今の電車", kana: "いまのでんしゃ", bn: "এখনকার ট্রেন", lesson: 29 },
    { kanji: "忘れ物", kana: "わすれもの", bn: "ভুলে যাওয়া জিনিস", lesson: 29 },
    { kanji: "このくらい", kana: "このくらい", bn: "এটা অনেক (বড়)", lesson: 29 },
    { kanji: "～側", kana: "～がわ", bn: "~সাইড", lesson: 29 },
    { kanji: "ポケット", kana: "ポケット", bn: "পকেট", lesson: 29 },
    { kanji: "～辺", kana: "～へん", bn: "চারপাশে~, ~প্রতিবেশি", lesson: 29 },
    { kanji: "覚えていません", kana: "おぼえていません", bn: "মনে করতে পারতেছিনা", lesson: 29 },
    { kanji: "網棚", kana: "あみだな", bn: "মাথার উপরের তাক", lesson: 29 },
    { kanji: "確か", kana: "たしか", bn: "অবশ্যই ঠিক", lesson: 29 },
    { kanji: "[ああ、] よかった", kana: "[ああ、] よかった", bn: "[আহ,] এটা ভালো ছিলো/ শুকরিয়া ধন্যবাদ", lesson: 29 },
    { kanji: "新宿", kana: "しんじゅく", bn: "শিনজুকু স্টেশন", lesson: 29 },
    { kanji: "地震", kana: "じしん", bn: "ভূমিকম্প", lesson: 29 },
    { kanji: "壁", kana: "かべ", bn: "দেয়াল", lesson: 29 },
    { kanji: "針", kana: "はり", bn: "ঘড়ির কাটা", lesson: 29 },
    { kanji: "指します", kana: "さします", bn: "বিন্দু, কেন্দ্রবিন্দু", lesson: 29 },
    { kanji: "駅前", kana: "えきまえ", bn: "স্টেশনের সামনে", lesson: 29 },
    { kanji: "倒れます", kana: "たおれます", bn: "ভেঙ্গে পড়া, পড়ে যাওয়া", lesson: 29 },
    { kanji: "西", kana: "にし", bn: "পশ্চিম", lesson: 29 },
    { kanji: "～の 方", kana: "～の ほう", bn: "দিক নির্দেশনা ~", lesson: 29 },
    { kanji: "燃えます", kana: "もえます", bn: "পোড়া", lesson: 29 },
    { kanji: "レポーター", kana: "レポーター", bn: "রিপোর্টার", lesson: 29 },
    { kanji: "込みます [道が～]", kana: "こみます [みちが～]", bn: "জনাকীর্ণ [রাস্তা]", lesson: 29 },
    { kanji: "空きます [道が～]", kana: "すきます [みちが～]", bn: "মানুষহীন [রাস্তা]", lesson: 29 },
    { kanji: "ひどい", kana: "ひどい", bn: "ভয়ানক, তীব্র", lesson: 29 },
    { kanji: "花が咲きます", kana: "はながさきます", bn: "ফুল ফোটা", lesson: 29 },
    { kanji: "手袋", kana: "てぶくろ", bn: "হাতের গ্লাভস বা মোজা", lesson: 29 },
    { kanji: "死にます", kana: "しにます", bn: "মারা যাওয়া", lesson: 29 },

    // Lesson 30 Data[span_4](start_span)[span_4](end_span)
    { kanji: "貼ります", kana: "はります", bn: "লাগানো, স্থাপন করা", lesson: 30 },
    { kanji: "掛けます", kana: "かけます", bn: "ঝুলানো", lesson: 30 },
    { kanji: "飾ります", kana: "かざります", bn: "প্রদর্শন করা, সাজানো", lesson: 30 },
    { kanji: "並べます", kana: "ならべます", bn: "সারিবদ্ধ করা", lesson: 30 },
    { kanji: "植えます", kana: "うえます", bn: "উদ্ভিদ, রোপণ করা", lesson: 30 },
    { kanji: "まとめます", kana: "まとめます", bn: "একসাথে করা, যোগ করা", lesson: 30 },
    { kanji: "戻します", kana: "もどします", bn: "ফিরত দেয়া", lesson: 30 },
    { kanji: "しまいます", kana: "しまいます", bn: "দুরে রাখা", lesson: 30 },
    { kanji: "決めます", kana: "きめます", bn: "সিদ্ধান্ত নেয়া", lesson: 30 },
    { kanji: "予習します", kana: "よしゅうします", bn: "অধ্যায়ের প্রস্তুতি", lesson: 30 },
    { kanji: "復習します", kana: "ふくしゅうします", bn: "অধ্যায় পর্যালোচনা", lesson: 30 },
    { kanji: "そのままにします", kana: "そのままにします", bn: "যেভাবে আছে সেভাবে রাখা", lesson: 30 },
    { kanji: "授業", kana: "じゅぎょう", bn: "শ্রেণি", lesson: 30 },
    { kanji: "講義", kana: "こうぎ", bn: "ভাষণ, শিক্ষা", lesson: 30 },
    { kanji: "ミーティング", kana: "ミーティング", bn: "সভা", lesson: 30 },
    { kanji: "予定", kana: "よてい", bn: "পরিকল্পনা", lesson: 30 },
    { kanji: "お知らせ", kana: "おしらせ", bn: "বিজ্ঞপ্তি", lesson: 30 },
    { kanji: "ガイドブック", kana: "ガイドブック", bn: "নির্দেশনা বই", lesson: 30 },
    { kanji: "カレンダー", kana: "カレンダー", bn: "দিনপঞ্জিকা", lesson: 30 },
    { kanji: "ポスター", kana: "ポスター", bn: "পোষ্টার", lesson: 30 },
    { kanji: "予定表", kana: "よていひょう", bn: "পরিকল্পনা", lesson: 30 },
    { kanji: "ごみ箱", kana: "ごみばこ", bn: "ময়লা ফেলার বাক্স", lesson: 30 },
    { kanji: "人形", kana: "にんぎょう", bn: "পুতুল", lesson: 30 },
    { kanji: "花瓶", kana: "かびん", bn: "ফুলদানী", lesson: 30 },
    { kanji: "鏡", kana: "かがみ", bn: "আয়না", lesson: 30 },
    { kanji: "引き出し", kana: "ひきだし", bn: "ড্রয়ার", lesson: 30 },
    { kanji: "玄関", kana: "げんかん", bn: "প্রবেশ পথ, সামনের দরজা", lesson: 30 },
    { kanji: "廊下", kana: "ろうか", bn: "করিডোর, হলওয়ে", lesson: 30 },
    { kanji: "壁", kana: "かべ", bn: "দেয়াল", lesson: 30 },
    { kanji: "池", kana: "いけ", bn: "পুকুর", lesson: 30 },
    { kanji: "元の所", kana: "もとのところ", bn: "মূল জায়গা", lesson: 30 },
    { kanji: "周り", kana: "まわり", bn: "চারপাশ", lesson: 30 },
    { kanji: "真ん中", kana: "まんなか", bn: "কেন্দ্রবিন্দু", lesson: 30 },
    { kanji: "隅", kana: "すみ", bn: "কর্ণার", lesson: 30 },
    { kanji: "まだ", kana: "まだ", bn: "এখনও", lesson: 30 },
    { kanji: "リュック", kana: "リュック", bn: "কাধ থেকে পিঠে ঝুলানোর ব্যাগ", lesson: 30 },
    { kanji: "非常袋", kana: "ひじょうぶくろ", bn: "জরুরি কিট বা জিনিস", lesson: 30 },
    { kanji: "非常時", kana: "ひじょうじ", bn: "জরুরি", lesson: 30 },
    { kanji: "生活します", kana: "せいかつします", bn: "জীবনযাপন করা", lesson: 30 },
    { kanji: "懐中電灯", kana: "かいちゅうでんとう", bn: "লাইট, ফ্লাশলাইট", lesson: 30 },
    { kanji: "～とか、～とか", kana: "～とか、～とか", bn: "~,~, এবং আরও অনেক কিছু", lesson: 30 },
    { kanji: "丸い", kana: "まるい", bn: "গোল, বৃত্ত", lesson: 30 },
    { kanji: "ある～", kana: "ある～", bn: "একটি নির্দিষ্ট ~", lesson: 30 },
    { kanji: "夢を見ます", kana: "ゆめをみます", bn: "স্বপ্ন", lesson: 30 },
    { kanji: "うれしい", kana: "うれしい", bn: "আনন্দিত, খুশি", lesson: 30 },
    { kanji: "嫌 [な]", kana: "いや [な]", bn: "ঘৃণা করা, অপছন্দ করা", lesson: 30 },
    { kanji: "すると", kana: "すると", bn: "এবং, পরে", lesson: 30 },
    { kanji: "目が覚めます", kana: "めがさめます", bn: "জেগে উঠা", lesson: 30 },
    { kanji: "知らせます", kana: "しらせます", bn: "তথা জানানো", lesson: 30 },
    { kanji: "相談します", kana: "そうだんします", bn: "আলোচনা করা", lesson: 30 },
    { kanji: "お子さん", kana: "おこさん", bn: "অন্যের বাচ্চা", lesson: 30 },
    { kanji: "ご苦労様", kana: "ごくろうさま", bn: "আপনার কঠোর পরিশ্রমের জন্য ধন্যবাদ", lesson: 30 },
    { kanji: "希望", kana: "きぼう", bn: "আশা, অনুরোধ", lesson: 30 },
    { kanji: "何かご希望がありますか？", kana: "なにかごきぼうがありますか？", bn: "আপনার কোন অনুরোধ আছে?", lesson: 30 },
    { kanji: "ミュージカル", kana: "ミュージカル", bn: "মিউজিক্যাল", lesson: 30 },
    { kanji: "これはいいですね", kana: "これはいいですね", bn: "এটা ভালো ধারনা / সুন্দর লাগছে", lesson: 30 },
    { kanji: "ブロードウエイ", kana: "ブロードウエイ", bn: "ব্রডওয়ে", lesson: 30 },
    { kanji: "月", kana: "つき", bn: "চাঁদ", lesson: 30 },
    { kanji: "地球", kana: "ちきゅう", bn: "পৃথিবী", lesson: 30 },
    { kanji: "交番", kana: "こうばん", bn: "পুলিশ স্টেশন", lesson: 30 },
    { kanji: "ほど", kana: "ほど", bn: "সম্পর্কে, শুধু", lesson: 30 },

    // Lesson 31 Data[span_5](start_span)[span_5](end_span)
    { kanji: "続けます", kana: "つづけます", bn: "চলমান", lesson: 31 },
    { kanji: "見つけます", kana: "みつけます", bn: "খোঁজা", lesson: 31 },
    { kanji: "取ります [休みを～]", kana: "とります [やすみを～]", bn: "নেওয়া [ছুটি]", lesson: 31 },
    { kanji: "受けます [試験を～]", kana: "うけます [しけんを～]", bn: "অংশগ্রহণ করা, দেওয়া [পরীক্ষা]", lesson: 31 },
    { kanji: "申し込みます", kana: "もうしこみます", bn: "আবেদন করা, ভর্তি ফর্ম", lesson: 31 },
    { kanji: "休憩します", kana: "きゅうけいします", bn: "বিশ্রাম নেওয়া", lesson: 31 },
    { kanji: "連休", kana: "れんきゅう", bn: "ধারাবাহিক ছুটির দিন", lesson: 31 },
    { kanji: "作文", kana: "さくぶん", bn: "রচনা", lesson: 31 },
    { kanji: "発表", kana: "はっぴょう", bn: "ঘোষণা, উপস্থাপন করা", lesson: 31 },
    { kanji: "展覧会", kana: "てんらんかい", bn: "প্রদর্শনী", lesson: 31 },
    { kanji: "結婚式", kana: "けっこんしき", bn: "বিয়ের অনুষ্ঠান", lesson: 31 },
    { kanji: "お葬式", kana: "おそうしき", bn: "অন্ত্যেষ্টিক্রিয়া", lesson: 31 },
    { kanji: "式", kana: "しき", bn: "অনুষ্ঠান", lesson: 31 },
    { kanji: "本社", kana: "ほんしゃ", bn: "প্রধান অফিস", lesson: 31 },
    { kanji: "支店", kana: "してん", bn: "শাখা অফিস", lesson: 31 },
    { kanji: "教会", kana: "きょうかい", bn: "চার্চ, গির্জা", lesson: 31 },
    { kanji: "大学院", kana: "だいがくいん", bn: "স্নাতক স্কুল", lesson: 31 },
    { kanji: "動物園", kana: "どうぶつえん", bn: "চিড়িয়াখানা", lesson: 31 },
    { kanji: "温泉", kana: "おんせん", bn: "গরম পানির ঝর্ণা, স্পা", lesson: 31 },
    { kanji: "帰り", kana: "かえり", bn: "ফেরত দেয়া", lesson: 31 },
    { kanji: "お子さん", kana: "おこさん", bn: "অন্যের বাচ্চা", lesson: 31 },
    { kanji: "～号", kana: "～ごう", bn: "ট্রেন নাম্বার, টাইফুন নাম্বার ইত্যাদি", lesson: 31 },
    { kanji: "～の方", kana: "～のほう", bn: "দিক নির্দেশক, ~দিকে", lesson: 31 },
    { kanji: "ずっと", kana: "ずっと", bn: "সম্পূর্ণ সময়", lesson: 31 },
    { kanji: "残ります", kana: "のこります", bn: "বাকী, ছেড়ে যাওয়া, পড়ে থাকা", lesson: 31 },
    { kanji: "入学試験", kana: "にゅうがくしけん", bn: "ভর্তি পরীক্ষা", lesson: 31 },
    { kanji: "月に", kana: "つきに", bn: "প্রতিমাস", lesson: 31 },
    { kanji: "村", kana: "むら", bn: "গ্রাম", lesson: 31 },
    { kanji: "卒業します", kana: "そつぎょうします", bn: "স্নাতক", lesson: 31 },
    { kanji: "映画館", kana: "えいがかん", bn: "সিনেমা হল, সিনেমা", lesson: 31 },
    { kanji: "閉じます", kana: "とじます", bn: "বন্ধ করা", lesson: 31 },
    { kanji: "都会", kana: "とかい", bn: "শহর", lesson: 31 },
    { kanji: "バリ", kana: "バリ", bn: "বালি (ইন্দোনেশিয়া)", lesson: 31 },
    { kanji: "ピカソ", kana: "ピカソ", bn: "পাবলো পিকাসো, স্প্যানিশ চিত্রশিল্পী (১৮৮১-১৯৭৩)", lesson: 31 },

    // Lesson 32 Data[span_6](start_span)[span_6](end_span)
    { kanji: "運動します", kana: "うんどうします", bn: "ব্যায়াম করা", lesson: 32 },
    { kanji: "成功します", kana: "せいこうします", bn: "সফল", lesson: 32 },
    { kanji: "失敗します [試験に～]", kana: "しっぱいします [しけんに～]", bn: "ব্যর্থ, ফেল করা [পরীক্ষায়]", lesson: 32 },
    { kanji: "合格します [試験に～]", kana: "ごうかくします [しけんに～]", bn: "[পরীক্ষায়] পাশ করা", lesson: 32 },
    { kanji: "やみます [雨が～]", kana: "やみます [あめが～]", bn: "[বৃষ্টি] থামা, বন্ধ", lesson: 32 },
    { kanji: "晴れます", kana: "はれます", bn: "পরিষ্কার (আবহাওয়া)", lesson: 32 },
    { kanji: "曇ります", kana: "くもります", bn: "মেঘাচ্ছন্ন", lesson: 32 },
    { kanji: "続きます [熱が～]", kana: "つづきます [ねつが～]", bn: "[জ্বর] চলমান, বেড়ে যাওয়া", lesson: 32 },
    { kanji: "引きます [風邪を～]", kana: "ひきます [かぜを～]", bn: "লাগা, ধরা [ঠান্ডা], সর্দি", lesson: 32 },
    { kanji: "冷やします", kana: "ひやします", bn: "শান্ত, শীতল", lesson: 32 },
    { kanji: "込みます [道が～]", kana: "こみます [みちが～]", bn: "[রাস্তা] জনাকীর্ণ", lesson: 32 },
    { kanji: "空きます [道が～]", kana: "すきます [みちが～]", bn: "[রাস্তা] জনমানবহীন, মানুষহীন", lesson: 32 },
    { kanji: "出ます [試合に／パーティーに～]", kana: "でます [しあいに／パーティーに～]", bn: "অংশগ্রহণ করা [খেলায় / পার্টিতে]", lesson: 32 },
    { kanji: "無理をします", kana: "むりをします", bn: "অতিরিক্ত জিনিস", lesson: 32 },
    { kanji: "十分 [な]", kana: "じゅうぶん [な]", bn: "পর্যাপ্ত, প্রচুর", lesson: 32 },
    { kanji: "おかしい", kana: "おかしい", bn: "হাস্যকর, অদ্ভুত", lesson: 32 },
    { kanji: "うるさい", kana: "うるさい", bn: "শব্দ, শোরগোল", lesson: 32 },
    { kanji: "先生", kana: "せんせい", bn: "ডাক্তার, শিক্ষক", lesson: 32 },
    { kanji: "火傷", kana: "やけど", bn: "পোড়া, পুড়ে যাওয়া", lesson: 32 },
    { kanji: "怪我", kana: "けが", bn: "ক্ষত, আঘাতপ্রাপ্ত", lesson: 32 },
    { kanji: "咳", kana: "せき", bn: "কাশি, কফ", lesson: 32 },
    { kanji: "インフルエンザ", kana: "インフルエンザ", bn: "ইনফ্লুয়েঞ্জা", lesson: 32 },
    { kanji: "空", kana: "そら", bn: "আকাশ", lesson: 32 },
    { kanji: "太陽", kana: "たいよう", bn: "সূর্য", lesson: 32 },
    { kanji: "星", kana: "ほし", bn: "তারা", lesson: 32 },
    { kanji: "風", kana: "かぜ", bn: "বায়ু", lesson: 32 },
    { kanji: "東", kana: "ひがし", bn: "পূর্ব", lesson: 32 },
    { kanji: "西", kana: "にし", bn: "পশ্চিম", lesson: 32 },
    { kanji: "南", kana: "みなみ", bn: "দক্ষিণ", lesson: 32 },
    { kanji: "北", kana: "きた", bn: "উত্তর", lesson: 32 },
    { kanji: "国際～", kana: "こくさい～", bn: "আন্তর্জাতিক~", lesson: 32 },
    { kanji: "水道", kana: "すいどう", bn: "কল, ট্যাপ, পানির কল", lesson: 32 },
    { kanji: "エンジン", kana: "エンジン", bn: "ইঞ্জিন", lesson: 32 },
    { kanji: "チーム", kana: "チーム", bn: "টিম, দল", lesson: 32 },
    { kanji: "今夜", kana: "こんや", bn: "এই সন্ধ্যা", lesson: 32 },
    { kanji: "夕方", kana: "ゆうがた", bn: "শেষবিকেল", lesson: 32 },
    { kanji: "前", kana: "まえ", bn: "অতীতকাল, পূর্বে", lesson: 32 },
    { kanji: "遅く", kana: "おそく", bn: "দেরি (সময়)", lesson: 32 },
    { kanji: "こんなに", kana: "こんなに", bn: "এই (অনেক)", lesson: 32 },
    { kanji: "そんなに", kana: "そんなに", bn: "ওই (অনেক) ২য় ব্যক্তির কাছে", lesson: 32 },
    { kanji: "あんなに", kana: "あんなに", bn: "ঐ (অনেক) ৩য় ব্যক্তির কাছে", lesson: 32 },
    { kanji: "元気", kana: "げんき", bn: "তেজ, শক্তি", lesson: 32 },
    { kanji: "胃", kana: "い", bn: "পেট", lesson: 32 },
    { kanji: "ストレス", kana: "ストレス", bn: "চাপ", lesson: 32 },
    { kanji: "それはいけませんね", kana: "それはいけませんね", bn: "আমি এটা শুনে দুঃখিত।", lesson: 32 },
    { kanji: "星占い", kana: "ほしうらない", bn: "জাতক, জ্যোতিষবিদ্যা", lesson: 32 },
    { kanji: "おうし座", kana: "おうしざ", bn: "বৃষরাশি", lesson: 32 },
    { kanji: "働きすぎ", kana: "はたらきすぎ", bn: "অতিরিক্ত কাজ", lesson: 32 },
    { kanji: "困ります", kana: "こまります", bn: "সমস্যায় পড়া, ঝামেলা", lesson: 32 },
    { kanji: "宝くじ", kana: "たからくじ", bn: "লটারি", lesson: 32 },
    { kanji: "当たります [宝くじが～]", kana: "あたります [たからくじが～]", bn: "বিজয়ী [লটারি]", lesson: 32 },
    { kanji: "健康", kana: "けんこう", bn: "স্বাস্থ্য", lesson: 32 },
    { kanji: "恋愛", kana: "れんあい", bn: "ভালোবাসা", lesson: 32 },
    { kanji: "恋人", kana: "こいびと", bn: "সুইটহার্ট, বয়ফ্রেন্ড, গার্লফ্রেন্ড", lesson: 32 },
    { kanji: "ラッキーアイテム", kana: "ラッキーアイテム", bn: "ভাগ্যবান জিনিস", lesson: 32 },
    { kanji: "石", kana: "いし", bn: "পাথর", lesson: 32 },
    { kanji: "ヨーロッパ", kana: "ヨーロッパ", bn: "ইউরোপ", lesson: 32 },

    // Lesson 33 Data[span_7](start_span)[span_7](end_span)
    { kanji: "逃げます", kana: "にげます", bn: "দৌড়ানো", lesson: 33 },
    { kanji: "騒ぎます", kana: "さわぎます", bn: "শোরগোল করা", lesson: 33 },
    { kanji: "諦めます", kana: "あきらめます", bn: "ছেড়ে দেয়া", lesson: 33 },
    { kanji: "投げます", kana: "なげます", bn: "নিক্ষেপ করা, ছুড়ে মারা", lesson: 33 },
    { kanji: "守ります", kana: "まもります", bn: "রাখা, অনুসরণ করা, মানা", lesson: 33 },
    { kanji: "始まります [式が～]", kana: "はじまります [しきが～]", bn: "[অনুষ্ঠান] শুরু করা, আরম্ভ করা", lesson: 33 },
    { kanji: "出席します [会議に～]", kana: "しゅっせきします [かいぎに～]", bn: "অংশ নেয়া [মিটিং এ]", lesson: 33 },
    { kanji: "伝えます", kana: "つたえます", bn: "বহন করা", lesson: 33 },
    { kanji: "注意します [車に～]", kana: "ちゅういします [くるまに～]", bn: "সতর্ক থাকা [গাড়ি থেকে]", lesson: 33 },
    { kanji: "外します [席を～]", kana: "はずします [せきを～]", bn: "দুরে [একজনের আসন বা সিট থেকে]", lesson: 33 },
    { kanji: "戻ります", kana: "もどります", bn: "ফিরে আসা", lesson: 33 },
    { kanji: "あります [電話が～]", kana: "あります [でんわが～]", bn: "আছে [ফোন কল]", lesson: 33 },
    { kanji: "リサイクルします", kana: "リサイクルします", bn: "পুনঃব্যবহার করা", lesson: 33 },
    { kanji: "だめ [な]", kana: "だめ [な]", bn: "ভালো না, নিষিদ্ধ, অসম্ভব", lesson: 33 },
    { kanji: "同じ", kana: "おなじ", bn: "একই, সেম", lesson: 33 },
    { kanji: "警察", kana: "けいさつ", bn: "পুলিশ স্টেশন, থানা", lesson: 33 },
    { kanji: "席", kana: "せき", bn: "আসন, সিট", lesson: 33 },
    { kanji: "マーク", kana: "マーク", bn: "মার্ক, চিহ্ন", lesson: 33 },
    { kanji: "ボール", kana: "ボール", bn: "বল", lesson: 33 },
    { kanji: "締め切り", kana: "しめきり", bn: "শেষতারিখ", lesson: 33 },
    { kanji: "規則", kana: "きそく", bn: "নিয়ম কানুন", lesson: 33 },
    { kanji: "危険", kana: "きけん", bn: "বিপজ্জনক", lesson: 33 },
    { kanji: "使用禁止", kana: "しようきんし", bn: "ব্যবহার করা যবে না", lesson: 33 },
    { kanji: "徐行", kana: "じょこう", bn: "ধীরে যাও", lesson: 33 },
    { kanji: "入口", kana: "いりぐち", bn: "প্রবেশদ্বার, প্রবেশপথ", lesson: 33 },
    { kanji: "出口", kana: "でぐち", bn: "বাহির হওয়ার পথ", lesson: 33 },
    { kanji: "非常口", kana: "ひじょうぐち", bn: "জরুরি কিট বা জিনিস", lesson: 33 },
    { kanji: "無料", kana: "むりょう", bn: "খরচ ছাড়া", lesson: 33 },
    { kanji: "割引", kana: "わりびき", bn: "ছাড়, ডিসকাউন্ট", lesson: 33 },
    { kanji: "飲み放題", kana: "のみほうだい", bn: "সবাই পান করতে পারেন", lesson: 33 },
    { kanji: "使用中", kana: "しようちゅう", bn: "ব্যবহার করা বা হচ্ছে", lesson: 33 },
    { kanji: "募集中", kana: "ぼしゅうちゅう", bn: "প্রার্থী / আবেদন চাওয়া", lesson: 33 },
    { kanji: "～中", kana: "～ちゅう", bn: "সাফিক্স হিসেবে বসে", lesson: 33 },
    { kanji: "どういう～", kana: "どういう～", bn: "কি (ধরনের ~)", lesson: 33 },
    { kanji: "いくら [～ても]", kana: "いくら [～ても]", bn: "যাইহোক ~, যদিও ~", lesson: 33 },
    { kanji: "もう", kana: "もう", bn: "আর না (নাবোধক)", lesson: 33 },
    { kanji: "あと～", kana: "あと～", bn: "~ পরে", lesson: 33 },
    { kanji: "～ほど", kana: "～ほど", bn: "~ সম্পর্কে", lesson: 33 },
    { kanji: "駐車違反", kana: "ちゅうしゃいはん", bn: "পার্কিং সীমালঙ্ঘন করা", lesson: 33 },
    { kanji: "罰金", kana: "ばっきん", bn: "জরিমানা", lesson: 33 },
    { kanji: "地震", kana: "じしん", bn: "ভূমিকম্প", lesson: 33 },
    { kanji: "起きます", kana: "おきます", bn: "ঘটা, সংঘটিত হওয়া", lesson: 33 },
    { kanji: "助け合います", kana: "たすけあいます", bn: "একে অপরকে সাহায্য", lesson: 33 },
    { kanji: "もともと", kana: "もともと", bn: "আসল, মূল", lesson: 33 },
    { kanji: "悲しい", kana: "かなしい", bn: "বিরহ, কষ্ট, দুঃখ", lesson: 33 },
    { kanji: "もっと", kana: "もっと", bn: "অধিক, আরও", lesson: 33 },
    { kanji: "挨拶", kana: "あいさつ", bn: "শুভেচ্ছা", lesson: 33 },
    { kanji: "相手", kana: "あいて", bn: "অন্য ব্যক্তি", lesson: 33 },
    { kanji: "気持ち", kana: "きもち", bn: "অনুভূতি", lesson: 33 },
    { kanji: "立ち入り禁止", kana: "たちいりきんし", bn: "প্রবেশ নিষেধ, বাইরে থাকুন", lesson: 33 },

    // Lesson 34 Data[span_8](start_span)[span_8](end_span)
    { kanji: "磨きます [歯を～]", kana: "みがきます [はを～]", bn: "ব্রাশ করা [দাঁত]", lesson: 34 },
    { kanji: "組み立てます", kana: "くみたてます", bn: "সমাবেশ, একত্র করা", lesson: 34 },
    { kanji: "折ります", kana: "おります", bn: "ভাঁজ, মোড়ানো, ভাঙ্গা", lesson: 34 },
    { kanji: "気がつきます [忘れ物に～]", kana: "きがつきます [わすれものに～]", bn: "খেয়াল করা, সচেতন থাকা [ছেড়ে যাওয়া জিনিসের প্রতি]", lesson: 34 },
    { kanji: "つけます [しょうゆを～]", kana: "つけます [しょうゆを～]", bn: "ঢালা [সয়া সস]", lesson: 34 },
    { kanji: "見つかります [かぎが～]", kana: "みつかります [かぎが～]", bn: "[চাবি] খুঁজে পাওয়া", lesson: 34 },
    { kanji: "質問します", kana: "しつもんします", bn: "প্রশ্ন জিজ্ঞাসা করা", lesson: 34 },
    { kanji: "差します [傘を～]", kana: "さします [かさを～]", bn: "রাখা [ছাতা]", lesson: 34 },
    { kanji: "スポーツクラブ", kana: "スポーツクラブ", bn: "ক্রিড়া সংঘ", lesson: 34 },
    { kanji: "お城", kana: "おしろ", bn: "দুর্গ", lesson: 34 },
    { kanji: "説明書", kana: "せつめいしょ", bn: "বর্ণনা করার বই, নির্দেশনা বই", lesson: 34 },
    { kanji: "図", kana: "ず", bn: "চিত্র, আকৃতি", lesson: 34 },
    { kanji: "線", kana: "せん", bn: "লাইন", lesson: 34 },
    { kanji: "矢印", kana: "やじるし", bn: "তীর চিহ্ন", lesson: 31 },
    { kanji: "黒", kana: "くろ", bn: "কালো", lesson: 31 },
    { kanji: "白", kana: "しろ", bn: "সাদা", lesson: 31 },
    { kanji: "赤", kana: "あか", bn: "লাল", lesson: 31 },
    { kanji: "青", kana: "あお", bn: "নীল", lesson: 31 },
    { kanji: "紺", kana: "こん", bn: "নেভি ব্লু, কালো নীল", lesson: 31 },
    { kanji: "黄色", kana: "きいろ", bn: "হলুদ", lesson: 31 },
    { kanji: "茶色", kana: "ちゃいろ", bn: "ব্রাউন", lesson: 31 },
    { kanji: "醤油", kana: "しょうゆ", bn: "সয়া, সয়া সস", lesson: 31 },
    { kanji: "ソース", kana: "ソース", bn: "সস", lesson: 31 },
    { kanji: "お客さん", kana: "おきゃくさん", bn: "দর্শক, অতিথি, ক্রেতা", lesson: 31 },
    { kanji: "～か～", kana: "～か～", bn: "~ অথবা ~", lesson: 31 },
    { kanji: "夕べ", kana: "ゆうべ", bn: "গত রাত", lesson: 31 },
    { kanji: "さっき", kana: "さっき", bn: "কিছুক্ষণ আগে", lesson: 31 },
    { kanji: "茶道", kana: "さどう", bn: "চা উৎসব", lesson: 31 },
    { kanji: "お茶をたてます", kana: "おちゃをたてます", bn: "চা তৈরি করা (চা উৎসবে)", lesson: 31 },
    { kanji: "先に", kana: "さきに", bn: "প্রথম, সামনে", lesson: 31 },
    { kanji: "載せます", kana: "のせます", bn: "স্থাপন করা, লোড করা", lesson: 31 },
    { kanji: "これでいいですか？", kana: "これでいいですか？", bn: "এটা কি ঠিক আছে ?", lesson: 31 },
    { kanji: "いかがですか？", kana: "いかがですか？", bn: "এটা কেমন ?", lesson: 34 },
    { kanji: "苦い", kana: "にがい", bn: "তিতা", lesson: 34 },
    { kanji: "親子どんぶり", kana: "おやこどんぶり", bn: "ভাতের সাথে মুরগির মাংশ ও ডিম", lesson: 34 },
    { kanji: "材料", kana: "ざいりょう", bn: "সরঞ্জাম, উপাদান", lesson: 34 },
    { kanji: "～分", kana: "～ぶん", bn: "অংশে ~ (পরিমাণ)", lesson: 34 },
    { kanji: "～グラム", kana: "～グラム", bn: "~ গ্রাম", lesson: 34 },
    { kanji: "～個", kana: "～こ", bn: "ছোট জিনিস গণনা করা", lesson: 34 },
    { kanji: "玉ねぎ", kana: "たまねぎ", bn: "পিয়াজ", lesson: 34 },
    { kanji: "4分の1", kana: "4ぶんの1", bn: "এক চতুর্থাংশ, চার ভাগের এক ভাগ", lesson: 34 },
    { kanji: "調味料", kana: "ちょうみりょう", bn: "টক, মশলা মেশানো", lesson: 34 },
    { kanji: "適当な大きさに", kana: "てきとうなおおきさに", bn: "ঠিক সাইজ", lesson: 34 },
    { kanji: "鍋", kana: "なべ", bn: "পাতিল, পট", lesson: 34 },
    { kanji: "火", kana: "ひ", bn: "আগুন, তাপ", lesson: 34 },
    { kanji: "火にかけます", kana: "ひにかけます", bn: "চুলায় আগুন দেয়া", lesson: 34 },
    { kanji: "煮ます", kana: "にます", bn: "রান্না, ফুটানো", lesson: 34 },
    { kanji: "煮えます", kana: "にえます", bn: "রান্না করা, ফুটানো", lesson: 34 },
    { kanji: "どんぶり", kana: "どんぶり", bn: "বোল বা বাটি", lesson: 34 },
    { kanji: "経ちます", kana: "たちます", bn: "সময় কাটানো", lesson: 34 },

    // Lesson 35 Data[span_9](start_span)[span_9](end_span)
    { kanji: "咲きます [花が～]", kana: "さきます [はなが～]", bn: "ফুল ফোটা", lesson: 35 },
    { kanji: "変わります [色が～]", kana: "かわります [いろが～]", bn: "রং পরিবর্তন হওয়া", lesson: 35 },
    { kanji: "困ります", kana: "こまります", bn: "সমস্যায় পড়া, ঝামেলা", lesson: 35 },
    { kanji: "付けます [丸を～]", kana: "つけます [まるを～]", bn: "বৃত্ত আঁকা, চিহ্ন করা, যোগ করা", lesson: 35 },
    { kanji: "直ります、治ります [病気が～] [故障が～]", kana: "なおります [びょうきが～] [こしょうが～]", bn: "সুস্থ হওয়া, সেরে উঠা [অসুস্থতা থেকে], মেরামত করা, ঠিক করা", lesson: 35 },
    { kanji: "クリックします", kana: "クリックします", bn: "ক্লিক করা", lesson: 35 },
    { kanji: "入力します", kana: "にゅうりょくします", bn: "ইনপুট করা, আমদানি করা", lesson: 35 },
    { kanji: "正しい", kana: "ただしい", bn: "ঠিক", lesson: 35 },
    { kanji: "島", kana: "しま", bn: "দ্বীপ", lesson: 35 },
    { kanji: "港", kana: "みなと", bn: "বন্দর, সমুদ্র বন্দর", lesson: 35 },
    { kanji: "近所", kana: "きんじょ", bn: "প্রতিবেশি", lesson: 35 },
    { kanji: "屋上", kana: "おくじょう", bn: "ছাদ", lesson: 35 },
    { kanji: "海外", kana: "かいがい", bn: "বিদেশ", lesson: 35 },
    { kanji: "山登り", kana: "やまのぼり", bn: "পর্বতারোহণ করা", lesson: 35 },
    { kanji: "歴史", kana: "れきし", bn: "ইতিহাস", lesson: 35 },
    { kanji: "機会", kana: "きかい", bn: "সুযোগ", lesson: 35 },
    { kanji: "許可", kana: "きょか", bn: "অনুমতি দেয়া", lesson: 35 },
    { kanji: "丸", kana: "まる", bn: "বৃত্ত, গোল", lesson: 35 },
    { kanji: "ふりがな", kana: "ふりがな", bn: "কাঞ্জির উপরে লেখা বর্ণ", lesson: 35 },
    { kanji: "設備", kana: "せつび", bn: "যন্ত্রপাতি, সুবিধা", lesson: 35 },
    { kanji: "レバー", kana: "レバー", bn: "লিভার", lesson: 35 },
    { kanji: "キー", kana: "キー", bn: "চাবি", lesson: 35 },
    { kanji: "カーテン", kana: "カーテン", bn: "পর্দা", lesson: 35 },
    { kanji: "ひも", kana: "ひも", bn: "দড়ি", lesson: 35 },
    { kanji: "炊飯器", kana: "すいはんき", bn: "রাইস কুকার", lesson: 35 },
    { kanji: "葉", kana: "は", bn: "পাতা", lesson: 35 },
    { kanji: "昔", kana: "むかし", bn: "প্রাচীনকাল", lesson: 35 },
    { kanji: "もっと", kana: "もっと", bn: "অধিক, আরও", lesson: 35 },
    { kanji: "これで 終わりましょう", kana: "これで おわりましょう", bn: "এখানে শেষ করা যাক।", lesson: 35 },
    { kanji: "それから", kana: "それから", bn: "এছাড়াও, এরপর", lesson: 35 },
    { kanji: "夜行バス", kana: "やこうバス", bn: "রাতের বাস", lesson: 35 },
    { kanji: "さあ", kana: "さあ", bn: "ভালো, আমাকে দেখতে দাও (অনিশ্চিত কিছু)", lesson: 35 },
    { kanji: "旅行社", kana: "りょこうしゃ", bn: "ট্রাভেল এজেন্সি", lesson: 35 },
    { kanji: "詳しい", kana: "くわしい", bn: "বিস্তারিত", lesson: 35 },
    { kanji: "スキー場", kana: "スキーじょう", bn: "স্কি রিসোর্ট, স্কি এলাকা", lesson: 35 },
    { kanji: "草津", kana: "くさつ", bn: "গুনমা প্রদেশের রিসোর্ট", lesson: 35 },
    { kanji: "志賀高原", kana: "しがこうげん", bn: "নাগানো প্রদেশের জাতীয় উদ্যান", lesson: 35 },
    { kanji: "朱", kana: "しゅ", bn: "লাল রং, সিন্দুর", lesson: 35 },
    { kanji: "交わります", kana: "まじわります", bn: "সঙ্গী থাকা", lesson: 35 },
    { kanji: "ことわざ", kana: "ことわざ", bn: "প্রবাদ", lesson: 35 },
    { kanji: "関係", kana: "かんけい", bn: "সম্পর্ক", lesson: 35 },
    { kanji: "仲よくします", kana: "なかよくします", bn: "ভালো সঙ্গী থাকা", lesson: 35 },
    { kanji: "必要 [な]", kana: "ひつよう [な]", bn: "প্রয়োজনীয়, দরকারি", lesson: 35 },
    { kanji: "箱根", kana: "はこね", bn: "কানাগাওয়া প্রদেশের ভ্রমন স্পট ও রিসোর্ট", lesson: 35 },
    { kanji: "日光", kana: "にっこう", bn: "তোচিগি প্রদেশের ভ্রমন স্পট", lesson: 35 },
    { kanji: "アフリカ", kana: "アフリカ", bn: "আফ্রিকা", lesson: 35 },
    { kanji: "マンガミュージアム", kana: "マンガミュージアム", bn: "কার্টুন জাদুঘর", lesson: 35 },
    { kanji: "みんなの学校", kana: "みんなのがっこう", bn: "একটি স্কুলের নাম", lesson: 35 },
    { kanji: "大黒ずし", kana: "だいこくずし", bn: "সুশি রেস্টুরেন্ট", lesson: 35 },
    { kanji: "IMC パソコン教室", kana: "IMC パソコンきょうしつ", bn: "IMC কম্পিউটার স্কুল", lesson: 35 },
    { kanji: "母の味", kana: "ははのあじ", bn: "একটি বইয়ের নাম", lesson: 35 },
    { kanji: "はる", kana: "はる", bn: "সেলুনের নাম", lesson: 35 },
    { kanji: "佐藤歯科", kana: "さとうしか", bn: "ডেন্টাল ক্লিনিকের নাম", lesson: 35 },
    { kanji: "毎日クッキング", kana: "まいにちクッキング", bn: "রান্নার স্কুল", lesson: 35 },
    { kanji: "向こう", kana: "むこう", bn: "ঐ দিকে, অন্য দিকে", lesson: 35 },

    // Lesson 36 Data[span_10](start_span)[span_10](end_span)
    { kanji: "遭います [事故に～]", kana: "あいます [じこに～]", bn: "দুর্ঘটনা ঘটা", lesson: 36 },
    { kanji: "貯金します", kana: "ちょきんします", bn: "টাকা সঞ্চয় করা", lesson: 36 },
    { kanji: "過ぎます [7時を～]", kana: "すぎます [7じを～]", bn: "অতিক্রম করা [৭টা]", lesson: 36 },
    { kanji: "慣れます [仕事に～]", kana: "なれます [しごとに～]", bn: "অভ্যস্ত হওয়া [কাজে]", lesson: 36 },
    { kanji: "腐ります [食べ物が～]", kana: "くさります [たべものが～]", bn: "[খাবার] পঁচে যাওয়া", lesson: 36 },
    { kanji: "剣道", kana: "けんどう", bn: "কেন্দো (জাপানি স্টাইলিস বাঁশের বেড়া)", lesson: 36 },
    { kanji: "柔道", kana: "じゅうどう", bn: "জুডো", lesson: 36 },
    { kanji: "ラッシュ", kana: "ラッシュ", bn: "ব্যস্ত সময়", lesson: 36 },
    { kanji: "宇宙", kana: "うちゅう", bn: "মহাকাশ, বিশ্ব", lesson: 36 },
    { kanji: "曲", kana: "きょく", bn: "গানের অংশ বা কলি", lesson: 36 },
    { kanji: "毎週", kana: "まいしゅう", bn: "প্রতি সপ্তাহ", lesson: 36 },
    { kanji: "毎月", kana: "まいつき", bn: "প্রতিমাস", lesson: 36 },
    { kanji: "毎年", kana: "まいとし、まいねん", bn: "প্রতিবছর", lesson: 36 },
    { kanji: "このごろ", kana: "このごろ", bn: "এইদিনগুলি", lesson: 36 },
    { kanji: "やっと", kana: "やっと", bn: "অবশেষে", lesson: 36 },
    { kanji: "かなり", kana: "かなり", bn: "স্বচ্ছ, পরিষ্কারভাবে", lesson: 36 },
    { kanji: "必ず", kana: "かならず", bn: "ব্যর্থতা ছাড়া, যেকোন উপায়ে", lesson: 36 },
    { kanji: "絶対に", kana: "ぜったいに", bn: "সম্পূর্ণভাবে, একেবারে", lesson: 36 },
    { kanji: "上手に", kana: "じょうずに", bn: "ভালো, দক্ষ", lesson: 36 },
    { kanji: "できるだけ", kana: "できるだけ", bn: "যতটুকু সম্ভব", lesson: 36 },
    { kanji: "ほとんど", kana: "ほとんど", bn: "প্রায় সব (হ্যাঁ বোধক), কদাচিৎ, একটুও না (না বোধক)", lesson: 36 },
    { kanji: "お客様", kana: "おきゃくさま", bn: "দর্শক, অতিথি, ক্রেতা, ক্লাইয়েণ্ট (সম্মানজনক ফর্ম おきゃくさん এর)", lesson: 36 },
    { kanji: "特別 [な]", kana: "とくべつ [な]", bn: "বিশেষ", lesson: 36 },
    { kanji: "していらっしゃいます", kana: "していらっしゃいます", bn: "করতেছেন (করা এর সম্মানজনক ফর্ম)", lesson: 36 },
    { kanji: "水泳", kana: "すいえい", bn: "সাঁতার", lesson: 36 },
    { kanji: "違います", kana: "ちがいます", bn: "ভিন্ন, আলাদা", lesson: 36 },
    { kanji: "使っていらっしゃるんですね", kana: "つかっていらっしゃるんですね", bn: "আপনি ব্যবহার করতেছেন, তাই নয় কি?", lesson: 36 },
    { kanji: "チャレンジします", kana: "チャレンジします", bn: "চ্যালেঞ্জ করা", lesson: 36 },
    { kanji: "気持ち", kana: "きもち", bn: "অনুভুতি, শক্তি, অবস্থা", lesson: 36 },
    { kanji: "乗り物", kana: "のりもの", bn: "গাড়ি, যানবাহন", lesson: 36 },
    { kanji: "～世紀", kana: "～せいき", bn: "~ শতাব্দী", lesson: 36 },
    { kanji: "遠く", kana: "とおく", bn: "দুর, দুরবর্তী এলাকা", lesson: 36 },
    { kanji: "珍しい", kana: "めずらしい", bn: "দুর্লভ, বিরল", lesson: 36 },
    { kanji: "汽車", kana: "きしゃ", bn: "চলতে সক্ষম, চারী", lesson: 36 },
    { kanji: "汽船", kana: "きせん", bn: "বাষ্প নৌকা", lesson: 36 },
    { kanji: "大勢の～", kana: "おおぜいの～", bn: "অনেক (মানুষ)", lesson: 36 },
    { kanji: "運びます", kana: "はこびます", bn: "বহন করা", lesson: 36 },
    { kanji: "利用します", kana: "りようします", bn: "ব্যবহার করা", lesson: 36 },
    { kanji: "自由に", kana: "じゆうに", bn: "স্বাধীনভাবে", lesson: 36 },
    { kanji: "ショパン", kana: "ショパン", bn: "শোপান, পোলশ সংগীত শিল্পী (১৮১০-১৮৪৯)", lesson: 36 },

    // Lesson 37 Data[span_11](start_span)[span_11](end_span)
    { kanji: "褒めます", kana: "ほめます", bn: "প্রশংসা করা", lesson: 37 },
    { kanji: "叱ります", kana: "しかります", bn: "ধমক দেয়া, তাড়িত", lesson: 37 },
    { kanji: "誘います", kana: "さそいます", bn: "নিমন্ত্রন করা, কাউকে দাওয়াত দেয়া", lesson: 37 },
    { kanji: "招待します", kana: "しょうたいします", bn: "নিমন্ত্রন করা", lesson: 37 },
    { kanji: "頼みます", kana: "たのみます", bn: "জিজ্ঞাসা করা, অনুরোধ", lesson: 37 },
    { kanji: "注意します", kana: "ちゅういします", bn: "সতর্ক করা, উপদেশ", lesson: 37 },
    { kanji: "盗ります", kana: "とります", bn: "চুরি, ডাকাতি", lesson: 37 },
    { kanji: "踏みます", kana: "ふみます", bn: "পায়ে পাড়া খাওয়া", lesson: 37 },
    { kanji: "壊します", kana: "こわします", bn: "ভেঙ্গে ফেলা, ধ্বংস করা", lesson: 37 },
    { kanji: "汚します", kana: "よごします", bn: "~ ময়লা করা", lesson: 37 },
    { kanji: "行います", kana: "おこないます", bn: "বহন করা, ধরে রাখা, অনুশীলন করা", lesson: 37 },
    { kanji: "輸出します", kana: "ゆしゅつします", bn: "রপ্তানি করা", lesson: 37 },
    { kanji: "輸入します", kana: "ゆにゅうします", bn: "আমদানি করা", lesson: 37 },
    { kanji: "翻訳します", kana: "ほんやくします", bn: "অনুবাদ করা", lesson: 37 },
    { kanji: "発明します", kana: "はつめいします", bn: "উদ্ভাবন করা", lesson: 37 },
    { kanji: "発見します", kana: "はっけんします", bn: "আবিষ্কার করা", lesson: 37 },
    { kanji: "米", kana: "こめ", bn: "ধান / চাল", lesson: 37 },
    { kanji: "麦", kana: "むぎ", bn: "বার্লি, গম", lesson: 37 },
    { kanji: "石油", kana: "せきゆ", bn: "তেল", lesson: 37 },
    { kanji: "原料", kana: "げんりょう", bn: "কাঁচা মাল", lesson: 37 },
    { kanji: "インスタントラーメン", kana: "インスタントラーメン", bn: "ঝটপট নুডুলস", lesson: 37 },
    { kanji: "デート", kana: "デート", bn: "তারিখ, দিন", lesson: 37 },
    { kanji: "泥棒", kana: "どろぼう", bn: "চোর, ডাকাত", lesson: 37 },
    { kanji: "警官", kana: "けいかん", bn: "পুলিশ", lesson: 37 },
    { kanji: "世界中", kana: "せかいじゅう", bn: "সারা পৃথিবী ব্যাপী", lesson: 37 },
    { kanji: "～中", kana: "～じゅう", bn: "সারা ~", lesson: 37 },
    { kanji: "～世紀", kana: "～せいき", bn: "~ শতাব্দী", lesson: 37 },
    { kanji: "何語", kana: "なにご", bn: "কোন ভাষা", lesson: 37 },
    { kanji: "だれか", kana: "だれか", bn: "যেকেউ", lesson: 37 },
    { kanji: "よかったですね。", kana: "よかったですね。", bn: "ভালো শব্দ ছিলো, এটা ভালো ছিলো", lesson: 37 },
    { kanji: "皆様", kana: "みなさま", bn: "ভদ্রমহিলা ও মহোদয়গণ (みなさん এর সম্মানজনক ফর্ম)", lesson: 37 },
    { kanji: "焼けます [家が～]", kana: "やけます [うちが～]", bn: "[বাড়ি] পোড়া", lesson: 37 },
    { kanji: "その後", kana: "そのご", bn: "এর পরে, পরে", lesson: 37 },
    { kanji: "世界遺産", kana: "せかいいさん", bn: "বিশ্ব ঐতিহ্য সংস্থা", lesson: 37 },
    { kanji: "～の一つ", kana: "～のひとつ", bn: "অন্যতম ~", lesson: 37 },
    { kanji: "金色", kana: "きんいろ", bn: "স্বর্ণ রং", lesson: 37 },
    { kanji: "本物", kana: "ほんもの", bn: "আসল জিনিস", lesson: 37 },
    { kanji: "金", kana: "きん", bn: "স্বর্ণ", lesson: 37 },
    { kanji: "～キロ", kana: "～キロ", bn: "~ কিলোগ্রাম, ~ কিলোমিটার", lesson: 37 },
    { kanji: "美しい", kana: "うつくしい", bn: "সুন্দর, দারুন", lesson: 37 },
    { kanji: "豪華 [な]", kana: "ごうか [な]", bn: "জমকালো, চমৎকার", lesson: 37 },
    { kanji: "彫刻", kana: "ちょうこく", bn: "ভাস্কর্য বানায় যে, ভাস্কর", lesson: 37 },
    { kanji: "言い伝え", kana: "いいつたえ", bn: "ঐতিহ্য, জীবন্তকিংবদন্তি", lesson: 37 },
    { kanji: "眠ります", kana: "ねむります", bn: "ঘুমানো", lesson: 37 },
    { kanji: "彫ります", kana: "ほります", bn: "ভাস্কর্য, মুর্তি", lesson: 37 },
    { kanji: "仲間", kana: "なかま", bn: "সহপাঠি, বন্ধু", lesson: 37 },
    { kanji: "しかし", kana: "しかし", bn: "যাইহোক, কিন্তু", lesson: 37 },
    { kanji: "その後", kana: "そのあと", bn: "এরপরে", lesson: 37 },
    { kanji: "一生懸命", kana: "いっしょうけんめい", bn: "সর্বোচ্চ দিয়ে চেষ্টা করা", lesson: 37 },
    { kanji: "ねずみ", kana: "ねずみ", bn: "ইঁদুর", lesson: 37 },
    { kanji: "一匹もいません", kana: "いっぴきもいません", bn: "এখানে একটাও নাই (ইঁদুর)", lesson: 37 },
    { kanji: "オリンピック", kana: "オリンピック", bn: "অলিম্পিক গেমস", lesson: 37 },
    { kanji: "ワールドカップ", kana: "ワールドカップ", bn: "বিশ্ব কাপ", lesson: 37 },
    { kanji: "東大寺", kana: "とうだいじ", bn: "তোদাইজি মন্দির", lesson: 37 },
    { kanji: "大仏", kana: "だいぶつ", bn: "গৌতম বৌদ্ধ মন্দির", lesson: 37 },
    { kanji: "江戸時代", kana: "えどじだい", bn: "এদো যুগ (১৬০৩-১৮৬৮)", lesson: 37 },
    { kanji: "ポルトガル", kana: "ポルトガル", bn: "পর্তুগাল", lesson: 37 },
    { kanji: "サウジアラビア", kana: "サウジアラビア", bn: "সৌদি আরব", lesson: 37 },
    { kanji: "ロシア", kana: "ロシア", bn: "রাশিয়া", lesson: 37 },
    { kanji: "眠り猫", kana: "ねむりねこ", bn: "ঘুমন্ত বিড়াল", lesson: 37 },
    { kanji: "左甚五郎", kana: "ひだりじんごろう", bn: "এদো যুগের বিখ্যাত জাপানি ভাস্কর (১৫৯৪-১৬৫১)", lesson: 37 },

    // Lesson 38 Data[span_12](start_span)[span_12](end_span)
    { kanji: "参加します [旅行に～]", kana: "さんかします [りょこうに～]", bn: "অংশগ্রহন করা [ভ্রমন], যোগ দেয়া", lesson: 38 },
    { kanji: "育てます", kana: "そだてます", bn: "লালনপালন করা, পরিচর্যা করা", lesson: 38 },
    { kanji: "運びます", kana: "はこびます", bn: "বহন করা, পরিবহন", lesson: 38 },
    { kanji: "入院します", kana: "にゅういんします", bn: "হাসপাতালে ভর্তি হওয়া", lesson: 38 },
    { kanji: "退院します", kana: "たいいんします", bn: "হাসপাতাল ছেড়ে যাওয়া", lesson: 38 },
    { kanji: "入れます [電源を～]", kana: "いれます [でんげんを～]", bn: "চালু করা [পাওয়ার সুইচ]", lesson: 38 },
    { kanji: "切ります [電源を～]", kana: "きります [でんげんを～]", bn: "বন্ধ করা [পাওয়ার সুইচ]", lesson: 38 },
    { kanji: "掛けます [かぎを～]", kana: "かけます [かぎを～]", bn: "তালা আটকানো, তালা মারা", lesson: 38 },
    { kanji: "つきます [うそを～]", kana: "つきます [うそを～]", bn: "বলা [মিথ্যা কথা]", lesson: 38 },
    { kanji: "気持ちがいい", kana: "きもちがいい", bn: "মনোরম, আনন্দদায়ক", lesson: 38 },
    { kanji: "気持ちが悪い", kana: "きもちがわるい", bn: "বিরক্তকর, অস্বস্তিকর", lesson: 38 },
    { kanji: "大きな～", kana: "おおきな～", bn: "বড় ~", lesson: 38 },
    { kanji: "小さな～", kana: "ちいさな～", bn: "ছোট ~", lesson: 38 },
    { kanji: "赤ちゃん", kana: "あかちゃん", bn: "শিশু", lesson: 38 },
    { kanji: "小学校", kana: "しょうがっこう", bn: "প্রাথমিক বিদ্যালয়", lesson: 38 },
    { kanji: "中学校", kana: "ちゅうがっこう", bn: "জুনিয়র হাই স্কুল", lesson: 38 },
    { kanji: "駅前", kana: "えきまえ", bn: "স্টেশনের সামনে", lesson: 38 },
    { kanji: "海岸", kana: "かいがん", bn: "সমুদ্রের তীর, সাগরপাড়", lesson: 38 },
    { kanji: "工場", kana: "こうじょう", bn: "কারখানা", lesson: 38 },
    { kanji: "村", kana: "むら", bn: "গ্রাম", lesson: 38 },
    { kanji: "かな", kana: "かな", bn: "হিরাগানা ও কাতাকানা স্ক্রিপ্ট", lesson: 38 },
    { kanji: "指輪", kana: "ゆびわ", bn: "আংটি", lesson: 38 },
    { kanji: "電源", kana: "でんげん", bn: "পাওয়ার সুইচ", lesson: 38 },
    { kanji: "習慣", kana: "しゅうかん", bn: "অভ্যাস", lesson: 38 },
    { kanji: "健康", kana: "けんこう", bn: "স্বাস্থ্য", lesson: 38 },
    { kanji: "～製", kana: "～せい", bn: "~ তৈরি", lesson: 38 },
    { kanji: "一昨年", kana: "おととし", bn: "গতবছরের আগের বছর", lesson: 38 },
    { kanji: "[あ、] いけない", kana: "[あ、] いけない", bn: "অপস! ওহ, না! (যখন কেউ ভুল করে, তখন বলে)", lesson: 38 },
    { kanji: "お先に 失礼します", kana: "おさきに しつれいします", bn: "মাফ করবেন (আপনার আগে চলে যাবো)", lesson: 38 },
    { kanji: "回覧", kana: "かいらん", bn: "বিজ্ঞপ্তি", lesson: 38 },
    { kanji: "研究室", kana: "けんきゅうしつ", bn: "পড়ার রুম, গবেষণাগার, অধ্যাপকের রুম", lesson: 38 },
    { kanji: "きちんと", kana: "きちんと", bn: "পরিষ্কার, সুন্দরভাবে", lesson: 38 },
    { kanji: "整理します", kana: "せいりします", bn: "ঝামেলা মেটানো, বাছাই করা", lesson: 38 },
    { kanji: "方法", kana: "ほうほう", bn: "পদ্ধতি", lesson: 38 },
    { kanji: "～という", kana: "～という", bn: "অভিহিত ~, নাম ~, বলা ~", lesson: 38 },
    { kanji: "～冊", kana: "～さつ", bn: "বই গণনাবাচক শব্দ", lesson: 38 },
    { kanji: "はんこ", kana: "はんこ", bn: "সিল, স্টাম্প", lesson: 38 },
    { kanji: "押します [はんこを～]", kana: "おします [はんこを～]", bn: "সিল [সংযোজন], স্টাম্প লাগানো", lesson: 38 },
    { kanji: "双子", kana: "ふたご", bn: "জোড়া", lesson: 38 },
    { kanji: "姉妹", kana: "しまい", bn: "বোন", lesson: 38 },
    { kanji: "5年生", kana: "5ねんせい", bn: "৫ম বছর, ৫ম গ্রেড", lesson: 38 },
    { kanji: "似ています", kana: "にています", bn: "সাদৃশ্য, মত", lesson: 38 },
    { kanji: "性格", kana: "せいかく", bn: "চরিত্র", lesson: 38 },
    { kanji: "おとなしい", kana: "おとなしい", bn: "শান্ত, ভদ্র", lesson: 38 },
    { kanji: "優しい", kana: "やさしい", bn: "দয়ালু, ভদ্র, কোমল হৃদয়বান", lesson: 38 },
    { kanji: "世話をします", kana: "せわをします", bn: "যত্ন নেওয়া", lesson: 38 },
    { kanji: "時間がたちます", kana: "じかんがたちます", bn: "সময় অতিক্রম করা", lesson: 38 },
    { kanji: "大好き [な]", kana: "だいすき [な]", bn: "খুব পছন্দ করা", lesson: 38 },
    { kanji: "～点", kana: "～てん", bn: "~ বিন্দু", lesson: 38 },
    { kanji: "気が強い", kana: "きがつよい", bn: "কঠিন, শক্তিশালী", lesson: 38 },
    { kanji: "喧嘩します", kana: "けんかします", bn: "ঝগড়া, যুদ্ধ বা মারামারি করা", lesson: 38 },
    { kanji: "不思議 [な]", kana: "ふしぎ [な]", bn: "রহস্যময়, অদ্ভুত", lesson: 38 },
    { kanji: "年齢", kana: "ねんれい", bn: "বয়স", lesson: 38 },
    { kanji: "しかた", kana: "しかた", bn: "উপায় (কোন কিছু করার)", lesson: 38 },
    { kanji: "原爆ドーム", kana: "げんばくドーム", bn: "হিরোশিমায় ফেলা এটম বোমা", lesson: 38 },
    { kanji: "出雲大社", kana: "いずもたいしゃ", bn: "শিমানে প্রদেশের ইজুমু শহরের মন্দির", lesson: 38 },
    { kanji: "チェンマイ", kana: "チェンマイ", bn: "চিয়ানমাই (থাইল্যান্ড)", lesson: 38 },

    // Lesson 39 Data[span_13](start_span)[span_13](end_span)
    { kanji: "答えます [質問に～]", kana: "こたえます [しつもんに～]", bn: "উত্তর দেয়া [প্রশ্নের]", lesson: 39 },
    { kanji: "倒れます [ビルが～]", kana: "たおれます [ビルが～]", bn: "পতিত হওয়া, পড়ে যাওয়া [বিল্ডিং]", lesson: 39 },
    { kanji: "通ります [道を～]", kana: "とおりまず [みちを～]", bn: "অতিক্রম করা [রাস্তা]", lesson: 39 },
    { kanji: "死にます", kana: "しにます", bn: "মারা যাওয়া", lesson: 39 },
    { kanji: "びっくりします", kana: "びっくりします", bn: "অবাক হওয়া", lesson: 39 },
    { kanji: "がっかりします", kana: "がっかりします", bn: "হতাশ হওয়া", lesson: 39 },
    { kanji: "安心します", kana: "あんしんします", bn: "মুক্তি পাওয়া, উপশম হওয়া", lesson: 39 },
    { kanji: "けんかします", kana: "けんかします", bn: "ঝগড়া করা, মারামারি করা", lesson: 39 },
    { kanji: "離婚します", kana: "りこんします", bn: "ডিভোর্স দেয়া", lesson: 39 },
    { kanji: "太ります", kana: "ふとります", bn: "মোটা হওয়া, ওজন বাড়া", lesson: 39 },
    { kanji: "痩せます", kana: "やせます", bn: "চিকন হওয়া, ওজন কমা", lesson: 39 },
    { kanji: "複雑 [な]", kana: "ふくざつ [な]", bn: "জটিল, কঠিন", lesson: 39 },
    { kanji: "邪魔 [な]", kana: "じゃま [な]", bn: "বাধা, পথে বাধা", lesson: 39 },
    { kanji: "硬い", kana: "かたい", bn: "শক্ত, কঠোর, খাঁটি", lesson: 39 },
    { kanji: "軟らかい", kana: "やわらかい", bn: "নরম, কোমল", lesson: 39 },
    { kanji: "汚い", kana: "きたない", bn: "ময়লা, আবর্জনা", lesson: 39 },
    { kanji: "嬉しい", kana: "うれしい", bn: "আনন্দিত, খুশি", lesson: 39 },
    { kanji: "悲しい", kana: "かなしい", bn: "দুঃখ, বেদনা, কষ্ট", lesson: 39 },
    { kanji: "恥ずかしい", kana: "はずかしい", bn: "লজ্জিত, বিব্রত", lesson: 39 },
    { kanji: "首相", kana: "しゅしょう", bn: "প্রধানমন্ত্রী", lesson: 39 },
    { kanji: "地震", kana: "じしん", bn: "ভূমিকম্প", lesson: 39 },
    { kanji: "津波", kana: "つなみ", bn: "সুনামি", lesson: 39 },
    { kanji: "台風", kana: "たいふう", bn: "টাইফুন, ঘূর্ণিঝড়", lesson: 39 },
    { kanji: "雷", kana: "かみなり", bn: "বজ্রপাত", lesson: 39 },
    { kanji: "火事", kana: "かじ", bn: "আগুন", lesson: 39 },
    { kanji: "事故", kana: "じこ", bn: "দুর্ঘটনা", lesson: 39 },
    { kanji: "ハイキング", kana: "ハイキング", bn: "হায়কিং করা", lesson: 39 },
    { kanji: "お見合い", kana: "おみあい", bn: "পাত্র দেখার অনুষ্ঠান", lesson: 39 },
    { kanji: "操作", kana: "そうさ", bn: "অপারেশন, পরিচালনা", lesson: 39 },
    { kanji: "会場", kana: "かいじょう", bn: "ভেন্যু, জায়গা", lesson: 39 },
    { kanji: "～代", kana: "～だい", bn: "বিল বা ভাড়া", lesson: 39 },
    { kanji: "～屋", kana: "～や", bn: "সাফিক্স হিসেবে বসে (e.g. baker, grocer)", lesson: 39 },
    { kanji: "フロント", kana: "フロント", bn: "সামনের টেবিল, অভ্যর্থনা টেবিল", lesson: 39 },
    { kanji: "～号室", kana: "～ごうしつ", bn: "রুম নাম্বার ~", lesson: 39 },
    { kanji: "タオル", kana: "タオル", bn: "তোয়ালে", lesson: 39 },
    { kanji: "石鹸", kana: "せっけん", bn: "সাবান", lesson: 39 },
    { kanji: "大勢", kana: "おおぜい", bn: "অনেক বেশি (মানুষ)", lesson: 39 },
    { kanji: "お疲れ様でした", kana: "おつかれさまでした", bn: "আপনার কঠোর পরিশ্রমের জন্য ধন্যবাদ", lesson: 39 },
    { kanji: "伺います", kana: "うかがいます", bn: "আমি আসতেছি (いきます এর সম্মানজনক রূপ)", lesson: 39 },
    { kanji: "途中で", kana: "とちゅうで", bn: "মাঝপথে, রাস্তায়", lesson: 39 },
    { kanji: "トラック", kana: "トラック", bn: "ট্রাক", lesson: 39 },
    { kanji: "ぶつかります", kana: "ぶつかります", bn: "হঠাৎ, আচমকা, ধাক্কা লাগা", lesson: 39 },
    { kanji: "大人", kana: "おとな", bn: "প্রাপ্ত বয়স্ক", lesson: 39 },
    { kanji: "しかし", kana: "しかし", bn: "যাইহোক, কিন্তু", lesson: 39 },
    { kanji: "また", kana: "また", bn: "এবং", lesson: 39 },
    { kanji: "洋服", kana: "ようふく", bn: "পশ্চিমা পোশাক", lesson: 39 },
    { kanji: "西洋化します", kana: "せいようかします", bn: "পশ্চিমা হওয়া", lesson: 39 },
    { kanji: "合います", kana: "あいます", bn: "ফিট, মানানসই", lesson: 39 },
    { kanji: "今では", kana: "いまでは", bn: "এখন", lesson: 39 },
    { kanji: "成年式", kana: "せいねんしき", bn: "বয়স উদযাপন আসছে", lesson: 39 },
    { kanji: "伝統的 [な]", kana: "でんとうてき [な]", bn: "ঐতিহাগত", lesson: 39 },

    // Lesson 40 Data[span_14](start_span)[span_14](end_span)
    { kanji: "数えます", kana: "かぞえます", bn: "গণনা করা", lesson: 40 },
    { kanji: "測ります、量ります", kana: "はかります", bn: "পরিমাপ করা, ওজন করা", lesson: 40 },
    { kanji: "確かめます", kana: "たしかめます", bn: "নিশ্চিত করা", lesson: 40 },
    { kanji: "合います [サイズが～]", kana: "あいます [サイズが～]", bn: "সাইজ ফিট হওয়া", lesson: 40 },
    { kanji: "出発します", kana: "しゅっぱつします", bn: "ছেড়ে যাওয়া", lesson: 40 },
    { kanji: "到着します", kana: "とうちゃくします", bn: "পৌঁছানো", lesson: 40 },
    { kanji: "酔います", kana: "よいます", bn: "নেশাগ্রস্ত", lesson: 40 },
    { kanji: "うまくいきます", kana: "うまくいきます", bn: "ভালো হওয়া", lesson: 40 },
    { kanji: "出ます [問題が～]", kana: "でます [もんだいが～]", bn: "[সমস্যায়] পড়া", lesson: 40 },
    { kanji: "相談します", kana: "そうだんします", bn: "আলোচনা করা", lesson: 40 },
    { kanji: "必要 [な]", kana: "ひつよう [な]", bn: "প্রয়োজনীয়", lesson: 40 },
    { kanji: "天気予報", kana: "てんきよほう", bn: "আবহাওয়ার সম্প্রচার", lesson: 40 },
    { kanji: "忘年会", kana: "ぼうねんかい", bn: "বছরের শেষ অনুষ্ঠান", lesson: 40 },
    { kanji: "新年会", kana: "しんねんかい", bn: "নববর্ষ অনুষ্ঠান", lesson: 40 },
    { kanji: "二次会", kana: "にじかい", bn: "দ্বিতীয় অনুষ্ঠান", lesson: 40 },
    { kanji: "発表会", kana: "はっぴょうかい", bn: "উপস্থাপন করা", lesson: 40 },
    { kanji: "大会", kana: "たいかい", bn: "র‍্যালি, কনভেনশন", lesson: 40 },
    { kanji: "マラソン", kana: "マラソン", bn: "ম্যারাথন", lesson: 40 },
    { kanji: "コンテスト", kana: "コンテスト", bn: "প্রতিযোগিতা", lesson: 40 },
    { kanji: "表", kana: "おもて", bn: "চেহারা, সামনে", lesson: 40 },
    { kanji: "裏", kana: "うら", bn: "পিছনের সাইড", lesson: 40 },
    { kanji: "間違い", kana: "まちがい", bn: "ভুল", lesson: 40 },
    { kanji: "傷", kana: "きず", bn: "খুঁত, ক্ষত", lesson: 40 },
    { kanji: "ズボン", kana: "ズボン", bn: "ট্রাউজার", lesson: 40 },
    { kanji: "お年寄り", kana: "おとしより", bn: "বয়স্ক ব্যক্তি", lesson: 40 },
    { kanji: "長さ", kana: "ながさ", bn: "দৈর্ঘ্য", lesson: 40 },
    { kanji: "重さ", kana: "おもさ", bn: "ওজন", lesson: 40 },
    { kanji: "高さ", kana: "たかさ", bn: "উচ্চতা", lesson: 40 },
    { kanji: "大きさ", kana: "おおきさ", bn: "সাইজ, বড়", lesson: 40 },
    { kanji: "～便", kana: "～びん", bn: "ফ্লাইট নাম্বার", lesson: 40 },
    { kanji: "～個", kana: "～こ", bn: "ছোট জিনিস গণনা করা", lesson: 40 },
    { kanji: "～本", kana: "～ほん、～ぼん、～ぽん", bn: "লম্বা জিনিস গণনা করা", lesson: 40 },
    { kanji: "～杯", kana: "～はい、～ばい、～ぱい", bn: "গ্লাস বা কাপ ~ (পূর্ণ গ্লাস বা কাপ গণনা করা)", lesson: 40 },
    { kanji: "～センチ", kana: "～センチ", bn: "~ সেন্টিমিটার", lesson: 40 },
    { kanji: "～ミリ", kana: "～ミリ", bn: "~ মিলিমিটার", lesson: 40 },
    { kanji: "～グラム", kana: "～グラム", bn: "~ গ্রাম", lesson: 40 },
    { kanji: "～以上", kana: "～いじょう", bn: "~ কম না, ~ বেশি", lesson: 40 },
    { kanji: "～以下", kana: "～いか", bn: "~ বেশি না, ~ কম", lesson: 40 },
    { kanji: "どうでしょうか。", kana: "どうでしょうか。", bn: "কেমন ?", lesson: 40 },
    { kanji: "テスト", kana: "テスト", bn: "পরীক্ষা", lesson: 40 },
    { kanji: "ところで", kana: "ところで", bn: "যাইহোক", lesson: 40 },
    { kanji: "いらっしゃいます", kana: "いらっしゃいます", bn: "আসা", lesson: 40 },
    { kanji: "様子", kana: "ようす", bn: "অবস্থা", lesson: 40 },
    { kanji: "成績", kana: "せいせき", bn: "ফলাফল", lesson: 40 },
    { kanji: "事件", kana: "じけん", bn: "ঘটনা", lesson: 40 },
    { kanji: "オートバイ", kana: "オートバイ", bn: "মোটরসাইকেল", lesson: 40 },
    { kanji: "爆弾", kana: "ばくだん", bn: "বোম", lesson: 40 },
    { kanji: "積みます", kana: "つみます", bn: "ভার, স্তূপ করা", lesson: 40 },
    { kanji: "運転者", kana: "うんてんしゃ", bn: "চালক", lesson: 40 },
    { kanji: "離れた", kana: "はなれた", bn: "দূরবর্তী", lesson: 40 },
    { kanji: "急に", kana: "きゅうに", bn: "হঠাৎ", lesson: 40 },
    { kanji: "動かします", kana: "うごかします", bn: "স্থানান্তর করা, শুরু করা", lesson: 40 },
    { kanji: "犯人", kana: "はんにん", bn: "অপরাধী", lesson: 40 },
    { kanji: "手に入れます", kana: "てにいれます", bn: "পাওয়া", lesson: 40 },
    { kanji: "今でも", kana: "いまでも", bn: "এখনই", lesson: 40 },
    { kanji: "噂します", kana: "うわさします", bn: "গল্প করা", lesson: 40 },
    { kanji: "足します", kana: "たします", bn: "যোগ করা", lesson: 40 },
    { kanji: "引きます", kana: "ひきます", bn: "বিয়োগ করা", lesson: 40 },
    { kanji: "掛けます", kana: "かけます", bn: "গুণ করা", lesson: 40 },
    { kanji: "割ります", kana: "わります", bn: "ভাগ করা", lesson: 40 },
    { kanji: "長崎", kana: "ながさき", bn: "নাগাসাকি", lesson: 40 },
    { kanji: "仙台", kana: "せんだい", bn: "সেনদাই", lesson: 40 },
    { kanji: "JL", kana: "JL", bn: "জাপান এয়ারলাইন", lesson: 40 },
    { kanji: "七夕祭り", kana: "たなばたまつり", bn: "তারা উৎসব", lesson: 40 },
    { kanji: "三角", kana: "さんかく", bn: "ত্রিভুজ", lesson: 40 },
    { kanji: "四角", kana: "しかく", bn: "চতুর্ভুজ", lesson: 40 },

    // Lesson 41 Data[span_15](start_span)[span_15](end_span)
    { kanji: "いただきます", kana: "いただきます", bn: "গ্রহণ করা (もらいます এর সম্মানজনক রূপ)", lesson: 41 },
    { kanji: "くださいます", kana: "くださいます", bn: "দেওয়া (くれます এর সম্মানজনক রূপ)", lesson: 41 },
    { kanji: "やります", kana: "やります", bn: "দেওয়া (ছোটদের, অধিনস্তদের, প্রাণী এবং উদ্ভিদকে)", lesson: 41 },
    { kanji: "上げます", kana: "あげます", bn: "বৃদ্ধি পাওয়া, উপরে উঠা", lesson: 41 },
    { kanji: "下げます", kana: "さげます", bn: "নিচে নামা, কমে যাওয়া", lesson: 41 },
    { kanji: "親切にします", kana: "しんせつにします", bn: "দয়ালু হওয়া", lesson: 41 },
    { kanji: "可愛い", kana: "かわいい", bn: "সুন্দর, চমৎকার", lesson: 41 },
    { kanji: "珍しい", kana: "めずらしい", bn: "বিরল, দুর্লভ", lesson: 41 },
    { kanji: "お祝い", kana: "おいわい", bn: "উদ্‌যাপন, উপহার", lesson: 41 },
    { kanji: "お年玉", kana: "おとしだま", bn: "নববর্ষের উপহার স্বরূপ টাকা দেয়া", lesson: 41 },
    { kanji: "[お]見舞い", kana: "[お]みまい", bn: "অসুস্থ ব্যক্তিকে দয়া বা করুনা দেখানো", lesson: 41 },
    { kanji: "興味", kana: "きょうみ", bn: "আগ্রহ", lesson: 41 },
    { kanji: "情報", kana: "じょうほう", bn: "তথ্য", lesson: 41 },
    { kanji: "文法", kana: "ぶんぽう", bn: "ব্যাকরণ", lesson: 41 },
    { kanji: "発音", kana: "はつおん", bn: "উচ্চারণ", lesson: 41 },
    { kanji: "去る", kana: "さる", bn: "বানর, বাঁদর", lesson: 41 },
    { kanji: "えさ", kana: "えさ", bn: "খাওয়ানো", lesson: 41 },
    { kanji: "玩具", kana: "おもちゃ", bn: "খেলনা", lesson: 41 },
    { kanji: "絵本", kana: "えほん", bn: "ছবির বই", lesson: 41 },
    { kanji: "絵葉書", kana: "えはがき", bn: "ছবি পোস্টকার্ড", lesson: 41 },
    { kanji: "ドライバー", kana: "ドライバー", bn: "স্ক্রুড্রাইভার", lesson: 41 },
    { kanji: "ハンカチ", kana: "ハンカチ", bn: "হাতরুমাল", lesson: 41 },
    { kanji: "靴下", kana: "くつした", bn: "পায়ের মোজা", lesson: 41 },
    { kanji: "手袋", kana: "てぶくろ", bn: "হাত মোজা বা গ্লাভস", lesson: 41 },
    { kanji: "幼稚園", kana: "ようちえん", bn: "কিন্ডারগার্টেন", lesson: 41 },
    { kanji: "暖房", kana: "だんぼう", bn: "গরম করা", lesson: 41 },
    { kanji: "冷房", kana: "れいぼう", bn: "এসি", lesson: 41 },
    { kanji: "温度", kana: "おんど", bn: "তাপমাত্রা", lesson: 41 },
    { kanji: "祖父", kana: "そふ", bn: "আমার দাদা", lesson: 41 },
    { kanji: "祖母", kana: "そぼ", bn: "আমার দাদী", lesson: 41 },
    { kanji: "孫", kana: "まご", bn: "আমার নাতি/ নাতনি", lesson: 41 },
    { kanji: "お孫さん", kana: "おまごさん", bn: "অন্যের নাতি/ নাতনি", lesson: 41 },
    { kanji: "おじ", kana: "おじ", bn: "আমার চাচা", lesson: 41 },
    { kanji: "おじさん", kana: "おじさん", bn: "অন্যের চাচা", lesson: 41 },
    { kanji: "おば", kana: "おば", bn: "আমার চাচি", lesson: 41 },
    { kanji: "おばさん", kana: "おばさん", bn: "অন্যের চাচি", lesson: 41 },
    { kanji: "管理人", kana: "かんりにん", bn: "তত্ত্বাবধায়ক, কেয়ারটেকার", lesson: 41 },
    { kanji: "～さん", kana: "～さん", bn: "কোন ব্যক্তির কাজ কে সম্মান জানাতে বসে", lesson: 41 },
    { kanji: "この間", kana: "このあいだ", bn: "অন্যদিন", lesson: 41 },
    { kanji: "ひとこと", kana: "ひとこと", bn: "কিছু কথা", lesson: 41 },
    { kanji: "～ずつ", kana: "～ずつ", bn: "প্রত্যেক", lesson: 41 },
    { kanji: "二人", kana: "ふたり", bn: "জোড়া", lesson: 41 },
    { kanji: "お宅", kana: "おたく", bn: "বাড়ি", lesson: 41 },
    { kanji: "どうぞ お幸せに", kana: "どうぞ おしあわせに", bn: "আমি আশা করি আপনি খুব খুশি হবেন।", lesson: 41 },
    { kanji: "昔話", kana: "むかしばなし", bn: "পুরান কাহিনি, কল্পকথা", lesson: 41 },
    { kanji: "ある～", kana: "ある～", bn: "~আছে, একটা~", lesson: 41 },
    { kanji: "子供たち", kana: "こどもたち", bn: "বাচ্চা", lesson: 41 },
    { kanji: "苛めます", kana: "いじめます", bn: "অসদাচরণ, খারাপ ব্যবহার করা", lesson: 41 },
    { kanji: "亀", kana: "かめ", bn: "কচ্ছপ", lesson: 41 },
    { kanji: "助けます", kana: "たすけます", bn: "সাহায্য, বাঁচানো", lesson: 41 },
    { kanji: "優しい", kana: "やさしい", bn: "দয়ালু, ভদ্র, কোমল হৃদয়", lesson: 41 },
    { kanji: "お姫様", kana: "おひめさま", bn: "রাজকুমারি", lesson: 41 },
    { kanji: "暮らします", kana: "くらします", bn: "জীবনযাপন করা, জীবিত", lesson: 41 },
    { kanji: "陸", kana: "りく", bn: "জমি, মাটি", lesson: 41 },
    { kanji: "すると", kana: "すると", bn: "এবং, তারপর", lesson: 41 },
    { kanji: "煙", kana: "けむり", bn: "ধোঁয়া", lesson: 41 },
    { kanji: "真っ白 [な]", kana: "まっしろ [な]", bn: "খাঁটি সাদা", lesson: 41 },
    { kanji: "中身", kana: "なかみ", bn: "সন্তুষ্ট", lesson: 41 },
    { kanji: "浦島太郎", kana: "うらしまたろう", bn: "পুরান কাহিনির প্রধান চরিত্র", lesson: 41 },
    { kanji: "単語", kana: "たんご", bn: "শব্দ, শব্দার্থ", lesson: 41 },
    { kanji: "預かります", kana: "あずかります", bn: "রাখা, বিশ্বাস রাখা", lesson: 41 },

    // Lesson 42 Data[span_16](start_span)[span_16](end_span)
    { kanji: "包みます", kana: "つつみます", bn: "মোড়ানো", lesson: 42 },
    { kanji: "沸かします", kana: "わかします", bn: "ফুটানো", lesson: 42 },
    { kanji: "混ぜます", kana: "まぜます", bn: "মিশানো", lesson: 42 },
    { kanji: "計算します", kana: "けいさんします", bn: "হিসাব করা", lesson: 42 },
    { kanji: "並びます", kana: "ならびます", bn: "লাইনে দাঁড়ানো", lesson: 42 },
    { kanji: "丈夫 [な]", kana: "じょうぶ [な]", bn: "স্বাস্থ্যবান, শক্ত", lesson: 42 },
    { kanji: "アパート", kana: "アパート", bn: "এপার্টমেন্ট, বাসা", lesson: 42 },
    { kanji: "弁護士", kana: "べんごし", bn: "আইনজীবী, এডভোকেট, জজ, ব্যারিস্টার", lesson: 42 },
    { kanji: "音楽家", kana: "おんがくか", bn: "মিউজিউশিয়ান", lesson: 42 },
    { kanji: "文化", kana: "ぶんか", bn: "সংস্কৃতি", lesson: 42 },
    { kanji: "子供たち", kana: "こどもたち", bn: "বাচ্চারা", lesson: 42 },
    { kanji: "自然", kana: "しぜん", bn: "প্রকৃতি", lesson: 42 },
    { kanji: "教育", kana: "きょういく", bn: "শিক্ষা", lesson: 42 },
    { kanji: "社会", kana: "しゃかい", bn: "সমাজ", lesson: 42 },
    { kanji: "政治", kana: "せいじ", bn: "রাজনীতি", lesson: 42 },
    { kanji: "法律", kana: "ほうりつ", bn: "আইন", lesson: 42 },
    { kanji: "戦争", kana: "せんそう", bn: "যুদ্ধ", lesson: 42 },
    { kanji: "平和", kana: "へいわ", bn: "শান্তি", lesson: 42 },
    { kanji: "目的", kana: "もくてき", bn: "উদ্দেশ্য, লক্ষ্য", lesson: 42 },
    { kanji: "論文", kana: "ろんぶん", bn: "থিসিস, গবেষণাপত্র", lesson: 42 },
    { kanji: "楽しみ", kana: "たのしみ", bn: "আনন্দিত, উপভোগ, প্রত্যাশা করা", lesson: 42 },
    { kanji: "ミキサー", kana: "ミキサー", bn: "মিশ্রক", lesson: 42 },
    { kanji: "薬缶、やかん", kana: "やかん", bn: "কেতলি", lesson: 42 },
    { kanji: "蓋", kana: "ふた", bn: "ঢাকনা, ক্যাপ, বোতলের মুখের ঢাকনা", lesson: 42 },
    { kanji: "栓抜き", kana: "せんぬき", bn: "বোতল খোলার যন্ত্র, কর্কস্ক্রু", lesson: 42 },
    { kanji: "缶きり", kana: "かんきり", bn: "ক্যান বা বোতল খোলার যন্ত্র", lesson: 42 },
    { kanji: "缶詰", kana: "かんづめ", bn: "বোতলজাত খাবার, কৌটার খাবার", lesson: 42 },
    { kanji: "熨斗袋", kana: "のしぶくろ", bn: "টাকার উপহারের খাম", lesson: 42 },
    { kanji: "風呂敷", kana: "ふろしき", bn: "কোন কিছু বহন করার জন্য কাপড় দিয়ে মোড়ানো", lesson: 42 },
    { kanji: "算盤", kana: "そろばん", bn: "গণনাকারী যন্ত্র", lesson: 42 },
    { kanji: "体温計", kana: "たいおんけい", bn: "থার্মোমিটার", lesson: 42 },
    { kanji: "材料", kana: "ざいりょう", bn: "উপাদান, উপকরণ", lesson: 42 },
    { kanji: "一生懸命", kana: "いっしょうけんめい", bn: "সর্বোচ্চ চেষ্টা করা", lesson: 42 },
    { kanji: "なぜ", kana: "なぜ", bn: "কেন", lesson: 42 },
    { kanji: "どのくらい", kana: "どのくらい", bn: "কি পরিমাণ, কতটুকু", lesson: 42 },
    { kanji: "出ます [ボーナスが～]", kana: "でます [ボーナスが～]", bn: "[বোনাস] পরিশোধ করা", lesson: 42 },
    { kanji: "半分", kana: "はんぶん", bn: "অর্ধেক", lesson: 42 },
    { kanji: "ローン", kana: "ローン", bn: "ঋণ, ধার", lesson: 42 },
    { kanji: "カップめん", kana: "カップめん", bn: "কাপ নুডুলস", lesson: 42 },
    { kanji: "～によって", kana: "～によって", bn: "~ দ্বারা", lesson: 42 },
    { kanji: "どんぶり", kana: "どんぶり", bn: "বোল বা বাটি", lesson: 42 },
    { kanji: "めん", kana: "めん", bn: "নুডুলস", lesson: 42 },
    { kanji: "広めます", kana: "ひろめます", bn: "বিস্তার, প্রসার", lesson: 42 },
    { kanji: "市場調査", kana: "しじょうちょうさ", bn: "বাজারের জরিপ", lesson: 42 },
    { kanji: "割ります", kana: "わります", bn: "ভাঙ্গা, ভাগ করা", lesson: 42 },
    { kanji: "チキンラーメン", kana: "チキンラーメン", bn: "চিকেন নুডুলস", lesson: 42 },
    { kanji: "安藤百福", kana: "あんどうももふく", bn: "জাপানি ব্যাবসায়ী এবং আবিষ্কারক (১৯১০-২০০৭)", lesson: 42 },
    { kanji: "国連", kana: "こくれん", bn: "জাতিসংঘ", lesson: 42 },
    { kanji: "エリーゼのために", kana: "エリーゼのために", bn: "এলিসের জন্য", lesson: 42 },
    { kanji: "ベートーベン", kana: "ベートーベン", bn: "এল. ভন ভেথোভেন, জার্মান সুরকারের নাম (১৭৭০-১৮২৭)", lesson: 42 },
    { kanji: "こどもニュース", kana: "こどもニュース", bn: "বাচ্চাদের অনুষ্ঠানের নাম", lesson: 42 },
    { kanji: "注ぎます", kana: "そそぎます", bn: "ঢালা", lesson: 42 },
    { kanji: "世界初", kana: "せかいはつ", bn: "পৃথিবীর প্রথম", lesson: 42 },

    // Lesson 43 Data[span_17](start_span)[span_17](end_span)
    { kanji: "増えます [輸出が～]", kana: "ふえます [ゆしゅつが～]", bn: "[রপ্তানি] বৃদ্ধি পাওয়া", lesson: 43 },
    { kanji: "減ります [輸出が～]", kana: "へります [ゆしゅつが～]", bn: "[রপ্তানি] হ্রাস পাওয়া", lesson: 43 },
    { kanji: "上がります [値段が～]", kana: "あがります [ねだんが～]", bn: "[দাম] বৃদ্ধি পাওয়া", lesson: 43 },
    { kanji: "下がります [値段が～]", kana: "さがります [ねだんが～]", bn: "[দাম] হ্রাস পাওয়া", lesson: 43 },
    { kanji: "切れます [ひもが～]", kana: "きれます [ひもが～]", bn: "[দড়ি] ছিঁড়ে যাওয়া", lesson: 43 },
    { kanji: "とれます [ボタンが～]", kana: "とれます [ボタンが～]", bn: "[বোতাম] খুলে যাওয়া", lesson: 43 },
    { kanji: "落ちます [荷物が～]", kana: "おちます [にもつが～]", bn: "[লাগেজ] পড়ে যাওয়া", lesson: 43 },
    { kanji: "無くなります [ガソリンが～]", kana: "なくなります [ガソリンが～]", bn: "[গ্যাস, পেট্রোল] হারানো, ফুরিয়ে যাওয়া", lesson: 43 },
    { kanji: "変 [な]", kana: "へん [な]", bn: "অদ্ভুত", lesson: 43 },
    { kanji: "幸せ [な]", kana: "しあわせ [な]", bn: "খুশি, সুখি", lesson: 43 },
    { kanji: "楽 [な]", kana: "らく [な]", bn: "সহজ", lesson: 43 },
    { kanji: "うまい", kana: "うまい", bn: "সুস্বাদু", lesson: 43 },
    { kanji: "まずい", kana: "まずい", bn: "সুস্বাদু নয়", lesson: 43 },
    { kanji: "つまらない", kana: "つまらない", bn: "বিরক্তকর, অনাগ্রহ", lesson: 43 },
    { kanji: "ガソリン", kana: "ガソリン", bn: "গ্যাস, পেট্রোল", lesson: 43 },
    { kanji: "火", kana: "ひ", bn: "আগুন", lesson: 43 },
    { kanji: "パンフレット", kana: "パンフレット", bn: "পুস্তিকা", lesson: 43 },
    { kanji: "今にも", kana: "いまにも", bn: "যেকোন সময়", lesson: 43 },
    { kanji: "わあ", kana: "わあ", bn: "ওয়াও ! / ওহহ !", lesson: 43 },
    { kanji: "センス", kana: "センス", bn: "চেতনা", lesson: 43 },
    { kanji: "会員", kana: "かいいん", bn: "সদস্য", lesson: 43 },
    { kanji: "適当", kana: "てきとう", bn: "উপযুক্ত, যথাযথ", lesson: 43 },
    { kanji: "ばら", kana: "ばら", bn: "গোলাপ", lesson: 43 },
    { kanji: "ドライブ", kana: "ドライブ", bn: "চালানো", lesson: 43 },
    { kanji: "理由", kana: "りゆう", bn: "কারণ", lesson: 43 },
    { kanji: "謝ります", kana: "あやまります", bn: "মাফ, ক্ষমা", lesson: 43 },
    { kanji: "知り合います", kana: "しりあいます", bn: "পরিচিত", lesson: 43 },
    { kanji: "年齢", kana: "ねんれい", bn: "বয়স", lesson: 43 },
    { kanji: "収入", kana: "しゅうにゅう", bn: "আয়", lesson: 43 },
    { kanji: "ぴったり", kana: "ぴったり", bn: "ঠিক, সঠিক", lesson: 43 },
    { kanji: "その上", kana: "そのうえ", bn: "তাছাড়া", lesson: 43 },
    { kanji: "厳しい", kana: "きびしい", bn: "তীব্র, যথাযথ", lesson: 43 },
    { kanji: "気が短い", kana: "きがみじかい", bn: "বদমজাজি", lesson: 43 },
    { kanji: "気が強い", kana: "きがつよい", bn: "প্রবল ইচ্ছা", lesson: 43 },
    { kanji: "気が弱い", kana: "きがよわい", bn: "ভীতু", lesson: 43 },
    { kanji: "活発", kana: "かっぱつ", bn: "সক্রিয়", lesson: 43 },
    { kanji: "誠実", kana: "せいじつ", bn: "আন্তরিক", lesson: 43 },
    { kanji: "我儘", kana: "わがまま", bn: "আত্মকেন্দ্রিক, স্বার্থপর", lesson: 43 },
    { kanji: "馬締め", kana: "うまじめ", bn: "হেবলা, ফালতু, বাজে", lesson: 43 },
    { kanji: "頑固", kana: "がんこ", bn: "একগুঁয়ে", lesson: 43 },
    { kanji: "素直", kana: "すなお", bn: "অনুগত", lesson: 43 },

    // Lesson 44 Data[span_18](start_span)[span_18](end_span)
    { kanji: "泣きます", kana: "なきます", bn: "কান্না করা", lesson: 44 },
    { kanji: "笑います", kana: "わらいます", bn: "হাসি", lesson: 44 },
    { kanji: "眠ります", kana: "ねむります", bn: "ঘুমানো", lesson: 44 },
    { kanji: "乾きます [シャツが～]", kana: "かわきます [シャツが～]", bn: "[শার্ট] শুকানো", lesson: 44 },
    { kanji: "濡れます [シャツが～]", kana: "ぬれます [シャツが～]", bn: "[শার্ট] ভেজা", lesson: 44 },
    { kanji: "滑ります", kana: "すべります", bn: "পিচ্ছিল খাওয়া, পিছলানো", lesson: 44 },
    { kanji: "起きます [事故が～]", kana: "おきます [じこが～]", bn: "[দুর্ঘটনা] ঘটা", lesson: 44 },
    { kanji: "調節します", kana: "ちょうせつします", bn: "খাপ খাওয়ানো", lesson: 44 },
    { kanji: "安全 [な]", kana: "あんぜん [な]", bn: "নিরাপদ", lesson: 44 },
    { kanji: "危険 [な]", kana: "きけん [な]", bn: "বিপজ্জনক", lesson: 44 },
    { kanji: "濃い", kana: "こい", bn: "কড়া (স্বাদ), কালো (রং), পুরু (তরল)", lesson: 44 },
    { kanji: "薄い", kana: "うすい", bn: "দুর্বল (স্বাদ), উজ্জ্বল (রং), পাতলা", lesson: 44 },
    { kanji: "厚い", kana: "あつい", bn: "মোটা", lesson: 44 },
    { kanji: "太い", kana: "ふとい", bn: "মোটা (বড় ব্যাস)", lesson: 44 },
    { kanji: "細い", kana: "ほそい", bn: "পাতলা (ছোট ব্যাস)", lesson: 44 },
    { kanji: "空気", kana: "くうき", bn: "বাতাস", lesson: 44 },
    { kanji: "涙", kana: "なみだ", bn: "চোখের জল", lesson: 44 },
    { kanji: "和食", kana: "わしょく", bn: "জাপানিজ খাবার", lesson: 44 },
    { kanji: "洋食", kana: "ようしょく", bn: "পশ্চিমা খাবার", lesson: 44 },
    { kanji: "おかず", kana: "おかず", bn: "অন্য খাবার", lesson: 44 },
    { kanji: "量", kana: "りょう", bn: "পরিমাণ", lesson: 44 },
    { kanji: "～倍", kana: "～ばい", bn: "~ বার", lesson: 44 },
    { kanji: "シングル", kana: "シングル", bn: "সিঙ্গেল রুম", lesson: 44 },
    { kanji: "ツイン", kana: "ツイン", bn: "ডাবল রুম", lesson: 44 },
    { kanji: "洗濯物", kana: "せんたくもの", bn: "ধৌত করা, লন্ড্রি", lesson: 44 },
    { kanji: "DVD", kana: "DVD", bn: "ডিভিডি", lesson: 44 },
    { kanji: "どうなさいますか。", kana: "どうなさいますか。", bn: "আমি আপনার জন্য কি করতে পারি ?", lesson: 44 },
    { kanji: "カット", kana: "カット", bn: "চুলের কাট", lesson: 44 },
    { kanji: "シャンプー", kana: "シャンプー", bn: "শ্যাম্পু", lesson: 44 },
    { kanji: "どういうふうになさいますか。", kana: "どういうふうになさいますか。", bn: "আপনি কিভাবে এটা করতে চান ?", lesson: 44 },
    { kanji: "ショート", kana: "ショート", bn: "খাটো, ছোট", lesson: 44 },
    { kanji: "～みたいにしてください", kana: "～みたいにしてください", bn: "~ এটা পছন্দ করেন", lesson: 44 },
    { kanji: "これでよろしいでしょうか。", kana: "これでよろしいでしょうか。", bn: "এটা কি ঠিক হবে ?", lesson: 44 },
    { kanji: "どうもお疲れ様でした。", kana: "どうもおつかれさまでした。", bn: "ধৈর্য ধরার জন্য আপনাকে ধন্যবাদ", lesson: 44 },
    { kanji: "嫌がります", kana: "いやがります", bn: "অপছন্দ", lesson: 44 },
    { kanji: "また", kana: "また", bn: "এবং", lesson: 44 },
    { kanji: "うまく", kana: "うまく", bn: "ভালো", lesson: 44 },
    { kanji: "順序", kana: "じゅんじょ", bn: "আদেশ", lesson: 44 },
    { kanji: "安心 [な]", kana: "あんしん [な]", bn: "মুক্ত, স্বাধীন, উপশম", lesson: 44 },
    { kanji: "表現", kana: "ひょうげん", bn: "অভিব্যক্তি", lesson: 44 },
    { kanji: "例えば", kana: "たとえば", bn: "উদাহরনস্বরূপ", lesson: 44 },
    { kanji: "別れます", kana: "わかれます", bn: "অংশ, আলাদা", lesson: 44 },
    { kanji: "これら", kana: "これら", bn: "এইগুলো", lesson: 44 },
    { kanji: "縁起が悪い", kana: "えんぎがわるい", bn: "দুর্ভাগ্য, খারাপ ভাগ্য", lesson: 44 },
    { kanji: "縁起がいい", kana: "えんぎがいい", bn: "ভাগ্যবান, সৌভাগ্যবান", lesson: 44 },
    { kanji: "細かい", kana: "こまかい", bn: "ছোট, খুচরা", lesson: 44 },
    { kanji: "箪笥", kana: "たんす", bn: "ড্রয়ারের বুক", lesson: 44 },
    { kanji: "丁寧", kana: "ていねい", bn: "নম্র, ভদ্র", lesson: 44 },
    { kanji: "パーマ", kana: "パーマ", bn: "স্থায়ী ঢেউ তোলা", lesson: 44 },
    { kanji: "反ります", kana: "そります", bn: "বাঁচানো, রক্ষা করা", lesson: 44 },
    { kanji: "ホテルひろしま", kana: "ホテルひろしま", bn: "হোটেলের নাম", lesson: 44 },

    // Lesson 45 Data[span_19](start_span)[span_19](end_span)
    { kanji: "信じます", kana: "しんじます", bn: "বিশ্বাস", lesson: 45 },
    { kanji: "キャンセルします", kana: "キャンセルします", bn: "বাতিল", lesson: 45 },
    { kanji: "知らせます", kana: "しらせます", bn: "তথা জানানো", lesson: 45 },
    { kanji: "保証書", kana: "ほしょうしょ", bn: "নিশ্চয়তা", lesson: 45 },
    { kanji: "領収書", kana: "りょうしゅうしょ", bn: "গ্রহণ করা", lesson: 45 },
    { kanji: "キャンプ", kana: "キャンプ", bn: "ক্যাম্প", lesson: 45 },
    { kanji: "中止", kana: "ちゅうし", bn: "বাতিল করা, স্থগিত করা", lesson: 45 },
    { kanji: "点", kana: "てん", bn: "পয়েন্ট, স্কোর", lesson: 45 },
    { kanji: "梅", kana: "うめ", bn: "বড়ই ফুল", lesson: 45 },
    { kanji: "110番", kana: "110ばん", bn: "১১০ নাম্বার", lesson: 45 },
    { kanji: "119番", kana: "119ばん", bn: "১১৯ নাম্বার", lesson: 45 },
    { kanji: "無理に", kana: "むりに", bn: "অকারণে, অযৌক্তিক", lesson: 45 },
    { kanji: "楽しみにしています", kana: "たのしみにしています", bn: "আশা করতেছি, অপেক্ষা করা", lesson: 45 },
    { kanji: "以上です", kana: "いじょうです", bn: "এ পর্যন্তই, শেষ করা।", lesson: 45 },
    { kanji: "贈り物", kana: "おくりもの", bn: "উপহার", lesson: 45 },
    { kanji: "間違い電話", kana: "まちがいでんわ", bn: "ভুল টেলিফোন নাম্বার", lesson: 45 },
    { kanji: "札", kana: "さつ", bn: "বিল, টাকা", lesson: 45 },
    { kanji: "ちゃんと", kana: "ちゃんと", bn: "নিয়মিত, যথাযথ", lesson: 45 },
    { kanji: "係員", kana: "かかりいん", bn: "সংগঠক, দায়িত্বপ্রাপ্ত", lesson: 45 },
    { kanji: "コース", kana: "コース", bn: "কোর্স, রাস্তা", lesson: 45 },
    { kanji: "スタート", kana: "スタート", bn: "চালু করা, শুরু করা", lesson: 45 },
    { kanji: "～位", kana: "～い", bn: "~ র‍্যাংকিং নাম্বার", lesson: 45 },
    { kanji: "優勝します", kana: "ゆうしょうします", bn: "জয়ী হওয়া, ১ম হওয়া", lesson: 45 },
    { kanji: "悩み", kana: "なやみ", bn: "সমস্যা, দুশ্চিন্তা", lesson: 45 },
    { kanji: "目覚まし [時計]", kana: "めざまし [どけい]", bn: "এলার্ম ঘড়ি", lesson: 45 },
    { kanji: "目が覚めます", kana: "めがさめます", bn: "জেগে উঠা", lesson: 45 },
    { kanji: "大学生", kana: "だいがくせい", bn: "বিশ্ববিদ্যালয় ছাত্র", lesson: 45 },
    { kanji: "回答", kana: "かいとう", bn: "উত্তর", lesson: 45 },
    { kanji: "鳴ります", kana: "なります", bn: "বাজে, শব্দ হওয়া", lesson: 45 },
    { kanji: "セットします", kana: "セットします", bn: "সেট করা", lesson: 45 },
    { kanji: "それでも", kana: "それでも", bn: "তবুও, তাসত্ত্বেও", lesson: 45 },

    // Lesson 46 Data[span_20](start_span)[span_20](end_span)
    { kanji: "渡します", kana: "わたします", bn: "হস্তান্তর করা", lesson: 46 },
    { kanji: "帰って来ます", kana: "かえってきます", bn: "ফিরে আসা", lesson: 46 },
    { kanji: "出ます [バスが～]", kana: "でます [バスが～]", bn: "[বাস] ছেড়ে যাওয়া", lesson: 46 },
    { kanji: "届きます [荷物が～]", kana: "とどけます [にもつが～]", bn: "[পার্সেল] পৌঁছানো", lesson: 46 },
    { kanji: "入学します [大学に～]", kana: "にゅうがくします [だいがくに～]", bn: "ভর্তি হওয়া [বিশ্ববিদ্যালয়ে]", lesson: 46 },
    { kanji: "卒業します [大学を～]", kana: "そつぎょうします [だいがくを～]", bn: "স্নাতক পাশ করা [বিশ্ববিদ্যালয় থেকে]", lesson: 46 },
    { kanji: "焼きます", kana: "やきます", bn: "সেঁকা, গ্রিল করা, রোস্ট করা", lesson: 46 },
    { kanji: "焼けます [パンが～ / 肉が～]", kana: "やけます [パンが～ / にくが～]", bn: "[রুটি] সেঁকা, [মাংস] রোস্ট করা, গ্রিল করা", lesson: 46 },
    { kanji: "留守", kana: "るす", bn: "অনুপস্থিত", lesson: 46 },
    { kanji: "宅配便", kana: "たくはいびん", bn: "হোম ডেলিভারি সেবা", lesson: 46 },
    { kanji: "原因", kana: "げんいん", bn: "কারণ", lesson: 46 },
    { kanji: "こちら", kana: "こちら", bn: "আমার কাছে", lesson: 46 },
    { kanji: "～の 所", kana: "～の ところ", bn: "কোথায় ~, ~ দ্বারা", lesson: 46 },
    { kanji: "半年", kana: "はんとし", bn: "অর্ধবছর", lesson: 46 },
    { kanji: "ちょうど", kana: "ちょうど", bn: "ঠিক", lesson: 46 },
    { kanji: "たった今", kana: "たったいま", bn: "এইমাত্র", lesson: 46 },
    { kanji: "今 いいですか。", kana: "いま いいですか。", bn: "আপনার কি এক মুহূর্ত সময় হবে ?", lesson: 46 },
    { kanji: "ガスサービスセンター", kana: "ガスサービスセンター", bn: "গ্যাস সার্ভিস সেন্টার", lesson: 46 },
    { kanji: "ガスレンジ", kana: "ガスレンジ", bn: "গ্যাস কুকার", lesson: 46 },
    { kanji: "具合", kana: "ぐあい", bn: "অবস্থা", lesson: 46 },
    { kanji: "申し訳 ありません", kana: "もうしわけ ありません", bn: "আমি দুঃখিত", lesson: 46 },
    { kanji: "どちら様でしょうか。", kana: "どちらさまでしょうか。", bn: "দয়া করে বলবেন, কে ?", lesson: 46 },
    { kanji: "お待たせしました", kana: "おまたせしました", bn: "আপনাকে অপেক্ষার জন্য দুঃখিত", lesson: 46 },
    { kanji: "向かいます", kana: "むかいます", bn: "সামনে ধাবিত হওয়া", lesson: 46 },
    { kanji: "ついて います", kana: "ついて います", bn: "ভাগ্যবান হওয়া", lesson: 46 },
    { kanji: "床", kana: "ゆか", bn: "তলা", lesson: 46 },
    { kanji: "転びます", kana: "ころびます", bn: "পতিত হওয়া, উল্টে পড়া", lesson: 46 },
    { kanji: "ベル", kana: "ベル", bn: "বেল", lesson: 46 },
    { kanji: "鳴ります", kana: "なります", bn: "আংটি", lesson: 46 },
    { kanji: "慌てて", kana: "あわてて", bn: "তাড়াহুড়ার মাঝে", lesson: 46 },
    { kanji: "順番に", kana: "じゅんばんに", bn: "ক্রমানুসারে", lesson: 46 },
    { kanji: "出来事", kana: "できごと", bn: "ঘটনা", lesson: 46 },
    { kanji: "注射", kana: "ちゅうしゃ", bn: "ইনজেকশন", lesson: 46 },
    { kanji: "食欲", kana: "しょくよく", bn: "ক্ষুধা", lesson: 46 },
    { kanji: "ステレオ", kana: "ステレオ", bn: "স্টেরিও", lesson: 46 },
    { kanji: "知識", kana: "ちしき", bn: "জ্ঞান", lesson: 46 },
    { kanji: "宝庫", kana: "ほうこ", bn: "ট্রেজারার", lesson: 46 },
    { kanji: "システム", kana: "システム", bn: "পদ্ধতি", lesson: 46 },
    { kanji: "キーワード", kana: "キーワード", bn: "কি ওয়ার্ড", lesson: 46 },
    { kanji: "一部分", kana: "いちぶぶん", bn: "এক অংশ", lesson: 46 },
    { kanji: "秒", kana: "びょう", bn: "সেকেন্ড", lesson: 46 },

    // Lesson 47 Data[span_21](start_span)[span_21](end_span)
    { kanji: "吹きます [風が～]", kana: "ふきます [かぜが～]", bn: "[বায়ু] প্রবাহ", lesson: 47 },
    { kanji: "燃えます [ごみが～]", kana: "もえます [ごみが～]", bn: "[ময়লা] পোড়া", lesson: 47 },
    { kanji: "亡くなります", kana: "なくなります", bn: "মারা যাওয়া", lesson: 47 },
    { kanji: "集まります [人が～]", kana: "あつまります [ひとが～]", bn: "[মানুষ] সমবেত হওয়া", lesson: 47 },
    { kanji: "別れます [人が～]", kana: "わかれます [ひとが～]", bn: "[মানুষ] আলাদা হওয়া", lesson: 47 },
    { kanji: "します [音／声が～] [味が～] [においが～]", kana: "します [おと／こえが～] [あじが～] [においが～]", bn: "[শব্দ] শুনতে পারা, স্বাদ পাওয়া, ঘ্রাণ পাওয়া", lesson: 47 },
    { kanji: "厳しい", kana: "きびしい", bn: "কঠোর, কড়া", lesson: 47 },
    { kanji: "酷い", kana: "ひどい", bn: "ভয়ানক", lesson: 47 },
    { kanji: "怖い", kana: "こわい", bn: "ভয়ংকর", lesson: 47 },
    { kanji: "実験", kana: "じっけん", bn: "গবেষণা, পরীক্ষা করা", lesson: 47 },
    { kanji: "データ", kana: "データ", bn: "তথ্য", lesson: 47 },
    { kanji: "人口", kana: "じんこう", bn: "জনসংখ্যা", lesson: 47 },
    { kanji: "におい", kana: "におい", bn: "ঘ্রাণ", lesson: 47 },
    { kanji: "科学", kana: "かがく", bn: "বিজ্ঞান", lesson: 47 },
    { kanji: "医学", kana: "いがく", bn: "চিকিৎসা বিজ্ঞান", lesson: 47 },
    { kanji: "文学", kana: "ぶんがく", bn: "সাহিত্য", lesson: 47 },
    { kanji: "パトカー", kana: "パトカー", bn: "পুলিশের গাড়ি", lesson: 47 },
    { kanji: "救急車", kana: "きゅうきゅうしゃ", bn: "এম্বুলেন্স", lesson: 47 },
    { kanji: "賛成", kana: "さんせい", bn: "অনুমোদন, সম্মতি দেয়া", lesson: 47 },
    { kanji: "反対", kana: "はんたい", bn: "বিরোধিতা, আপত্তি", lesson: 47 },
    { kanji: "大統領", kana: "だいとうりょう", bn: "রাষ্ট্রপতি", lesson: 47 },
    { kanji: "～によると", kana: "～によると", bn: "~ অনুসারে, ~ অনুযায়ী", lesson: 47 },
    { kanji: "婚約します", kana: "こんやくします", bn: "বাগদান করা", lesson: 47 },
    { kanji: "どうも", kana: "どうも", bn: "এটা মনে হচ্ছে যে", lesson: 47 },
    { kanji: "恋人", kana: "こいびと", bn: "ভালোবাসার মানুষ", lesson: 47 },
    { kanji: "相手", kana: "あいて", bn: "অন্য ব্যক্তি", lesson: 47 },
    { kanji: "知り合います", kana: "しりあいます", bn: "পরিচিত", lesson: 47 },
    { kanji: "化粧", kana: "けしょう", bn: "মেকআপ", lesson: 47 },
    { kanji: "世話をします", kana: "せわをします", bn: "যত্ন নেওয়া", lesson: 47 },
    { kanji: "女性", kana: "じょせい", bn: "মহিলা", lesson: 47 },
    { kanji: "男性", kana: "だんせい", bn: "পুরুষ", lesson: 47 },
    { kanji: "長生き", kana: "ながいき", bn: "দীর্ঘ জীবন, দীর্ঘ সময়", lesson: 47 },
    { kanji: "理由", kana: "りゆう", bn: "কারণ", lesson: 47 },
    { kanji: "関係", kana: "かんけい", bn: "সম্পর্ক", lesson: 47 },
    { kanji: "平均", kana: "へいきん", bn: "গড়", lesson: 47 },
    { kanji: "寿命", kana: "じゅみょう", bn: "জীবনকাল", lesson: 47 },
    { kanji: "比べます", kana: "くらべます", bn: "তুলনা করা", lesson: 47 },
    { kanji: "博士", kana: "はかせ", bn: "ডাক্তার", lesson: 47 },
    { kanji: "脳", kana: "のう", bn: "ব্রেইন, বুদ্ধি", lesson: 47 },
    { kanji: "ホルモン", kana: "ホルモン", bn: "হরমোন", lesson: 47 },
    { kanji: "化粧品", kana: "けしょうひん", bn: "কসমেটিকস", lesson: 47 },
    { kanji: "吠えます", kana: "ほえます", bn: "বাকল", lesson: 47 },
    { kanji: "げらげら", kana: "げらげら", bn: "অট্টহাসি", lesson: 47 },
    { kanji: "しくしく", kana: "しくしく", bn: "ফোপানো", lesson: 47 },
    { kanji: "きょろきょろ", kana: "きょろきょろ", bn: "অবিরত", lesson: 47 },
    { kanji: "すらすら", kana: "すらすら", bn: "অর্গল", lesson: 47 },
    { kanji: "ざらざら", kana: "ざらざら", bn: "মোটামুটি", lesson: 47 },
    { kanji: "べたべた", kana: "べたべた", bn: "আঠালো", lesson: 47 },
    { kanji: "つるつる", kana: "つるつる", bn: "মসৃণ", lesson: 47 },

    // Lesson 48 Data[span_22](start_span)[span_22](end_span)
    { kanji: "降ろします、下ろします", kana: "おろします", bn: "নামিয়ে রাখা, খালি করা, নামানো", lesson: 48 },
    { kanji: "届けます", kana: "とどけます", bn: "পাঠানো, পৌঁছানো", lesson: 48 },
    { kanji: "世話をします", kana: "せわをします", bn: "যত্ন নেওয়া", lesson: 48 },
    { kanji: "録音します", kana: "ろくおんします", bn: "রেকর্ড, সংরক্ষণ করা", lesson: 48 },
    { kanji: "嫌 [な]", kana: "いや [な]", bn: "অনিচ্ছুক", lesson: 48 },
    { kanji: "塾", kana: "じゅく", bn: "কোচিং স্কুল", lesson: 48 },
    { kanji: "生徒", kana: "せいと", bn: "ছাত্র, পুতলি", lesson: 48 },
    { kanji: "ファイル", kana: "ファイル", bn: "নথি, ফাইল", lesson: 48 },
    { kanji: "自由に", kana: "じゆうに", bn: "স্বাধীনভাবে", lesson: 48 },
    { kanji: "～間", kana: "～かん", bn: "~ জন্য", lesson: 48 },
    { kanji: "いいことですね。", kana: "いいことですね。", bn: "এটা ভালো", lesson: 48 },
    { kanji: "お忙しいですか。", kana: "おいそがしいですか。", bn: "আপনি কি ব্যস্ত?", lesson: 48 },
    { kanji: "営業", kana: "えいぎょう", bn: "ব্যবসা, বিক্রয়", lesson: 48 },
    { kanji: "それまでに", kana: "それまでに", bn: "ততক্ষণে", lesson: 48 },
    { kanji: "かまいません", kana: "かまいません", bn: "ঠিক আছে / কিছু মনে করিনি।", lesson: 48 },
    { kanji: "楽しみます", kana: "たのしみます", bn: "উপভোগ করা", lesson: 48 },
    { kanji: "親", kana: "おや", bn: "বাবা মা", lesson: 48 },
    { kanji: "小学生", kana: "しょうがくせい", bn: "প্রাইমারি বিদ্যালয়ের ছাত্র", lesson: 48 },
    { kanji: "～パーセント", kana: "～パーセント", bn: "~ শতাংশ", lesson: 48 },
    { kanji: "その次", kana: "そのつぎ", bn: "পরবর্তী", lesson: 48 },
    { kanji: "習字", kana: "しゅうじ", bn: "হস্তলিপি, লিপিবিদ্যা", lesson: 48 },
    { kanji: "普通の", kana: "ふつうの", bn: "সাধারণত", lesson: 48 },
    { kanji: "久しぶり", kana: "ひさしぶり", bn: "অনেকদিন পর", lesson: 48 },
    { kanji: "スピード", kana: "スピード", bn: "গতি, স্পিড", lesson: 48 },
    { kanji: "競争します", kana: "きょうそうします", bn: "প্রতিদ্বন্দ্বিতা করা", lesson: 48 },
    { kanji: "サーカス", kana: "サーカス", bn: "সার্কাস", lesson: 48 },
    { kanji: "芸", kana: "げい", bn: "অভিনয়, সম্পাদন", lesson: 48 },
    { kanji: "姿", kana: "すがた", bn: "ব্যক্তিত্ব, চরিত্র, উপস্থিতি", lesson: 48 },
    { kanji: "心", kana: "こころ", bn: "হৃদয়, মন", lesson: 48 },
    { kanji: "捕らえます", kana: "とらえます", bn: "ধরা", lesson: 48 },

    // Lesson 49 Data[span_23](start_span)[span_23](end_span)
    { kanji: "利用します", kana: "りようします", bn: "ব্যবহার করা", lesson: 49 },
    { kanji: "勤めます [会社に～]", kana: "つとめます [かいしゃに～]", bn: "কাজ করা [কোম্পানিতে]", lesson: 49 },
    { kanji: "掛けます [いすに～]", kana: "かけます [いすに～]", bn: "বসা [চেয়ারে]", lesson: 49 },
    { kanji: "過ごします", kana: "すごします", bn: "সময় কাটানো", lesson: 49 },
    { kanji: "いらっしゃいます", kana: "いらっしゃいます", bn: "থাকা, যাওয়া, আসা (います, いきます, きます এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "召し上がります", kana: "めしあがります", bn: "খাওয়া, পান করা (たべます, のみます এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "おっしゃいます", kana: "おっしゃいます", bn: "(একজনের নাম) বলা (いいます এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "なさいます", kana: "なさいます", bn: "করা বা খেলা (します এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "ご覧になります", kana: "ごらんになります", bn: "দেখা, তাকানো (みます এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "ご存じです", kana: "ごぞんじです", bn: "জানা (しっています এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "挨拶", kana: "あいさつ", bn: "শুভেচ্ছা, ঠিকানা দেয়া", lesson: 49 },
    { kanji: "旅館", kana: "りょかん", bn: "জাপানিজ হোটেল", lesson: 49 },
    { kanji: "バス停", kana: "バスてい", bn: "বাস স্টপেজ", lesson: 49 },
    { kanji: "奥様", kana: "おくさま", bn: "অন্যের বউ (おくさん এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "たまに", kana: "たまに", bn: "কোন এক সময়, মাঝেমাঝে", lesson: 49 },
    { kanji: "どなたでも", kana: "どなたでも", bn: "যেকেউ (だれでも এর সম্মানজনক রূপ)", lesson: 49 },
    { kanji: "世界的に", kana: "せかいてきに", bn: "বিশ্বব্যাপী", lesson: 49 },
    { kanji: "作家", kana: "さっか", bn: "লেখক", lesson: 49 },
    { kanji: "長男", kana: "ちょうなん", bn: "বড় ছেলে", lesson: 49 },
    { kanji: "障害", kana: "しょうがい", bn: "প্রতিবন্ধী, ত্রুটি", lesson: 49 },
    { kanji: "作曲", kana: "さっきょく", bn: "সুরকার", lesson: 49 },
    { kanji: "活動", kana: "かつどう", bn: "কার্যকলাপ", lesson: 49 },
    { kanji: "～年～組", kana: "～ねん～くみ", bn: "~ক্লাস ~গ্রেড", lesson: 49 },
    { kanji: "出します [熱を～]", kana: "だします [ねつを～]", bn: "[জ্বর] বেড়ে যাওয়া, চলমান", lesson: 49 },
    { kanji: "よろしくお伝えください", kana: "よろしくおつたえください", bn: "আমার শুভেচ্ছা দিন / হ্যালো বলুন", lesson: 49 },
    { kanji: "経歴", kana: "けいれき", bn: "প্রেক্ষাপট, পটভূমি", lesson: 49 },
    { kanji: "医学部", kana: "いがくぶ", bn: "চিকিৎসা বিভাগ", lesson: 49 },
    { kanji: "目指します", kana: "めざします", bn: "লক্ষ্য স্থির করা", lesson: 49 },
    { kanji: "進みます", kana: "すすみます", bn: "চলতে থাকা, করতে থাকা", lesson: 49 },
    { kanji: "iPS細胞", kana: "iPSさいぼう", bn: "আইপিএস সেল", lesson: 49 },
    { kanji: "開発します", kana: "かいはつします", bn: "বিকাশ, সৃষ্টি", lesson: 49 },
    { kanji: "マウス", kana: "マウス", bn: "মাউস", lesson: 49 },
    { kanji: "ヒト", kana: "ヒト", bn: "মানব", lesson: 49 },
    { kanji: "受賞します", kana: "じゅしょうします", bn: "পুরস্কার দেয়া হবে", lesson: 49 },
    { kanji: "講演会", kana: "こうえんかい", bn: "বক্তৃতা সভা", lesson: 49 },
    { kanji: "山中伸弥", kana: "やまなかしんや", bn: "জাপানি চিকিৎসা বিজ্ঞানী (১৯৬২-)", lesson: 49 },
    { kanji: "ノーベル賞", kana: "ノーベルしょう", bn: "নোবেল পুরস্কার", lesson: 49 },
    { kanji: "寄ります", kana: "よります", bn: "চেষ্টা করা, কাছাকাছি আসা, থামিয়ে দেয়া", lesson: 49 },
    { kanji: "灰皿", kana: "はいざら", bn: "ছাইদানি", lesson: 49 },
    { kanji: "貿易", kana: "ぼうえき", bn: "বাণিজ্য", lesson: 49 },
    { kanji: "帰りに", kana: "かえりに", bn: "ফিরে যাবার সময়", lesson: 49 },
    { kanji: "ちっとも", kana: "ちっとも", bn: "একদমই না", lesson: 49 },
    { kanji: "遠慮", kana: "えんりょ", bn: "দ্বিধা ছাড়া", lesson: 49 },
    { kanji: "講師", kana: "こうし", bn: "লেকচার, বক্তৃতা", lesson: 49 },
    { kanji: "多くの", kana: "おおくの", bn: "অনেক, প্রচুর", lesson: 49 },
    { kanji: "作品", kana: "さくひん", bn: "কাজ", lesson: 49 },
    { kanji: "それでは", kana: "それでは", bn: "ভালো, তারপর, তাই", lesson: 49 },
    { kanji: "ひまわり小学校", kana: "ひまわりしょうがっこう", bn: "হিমাওয়ারি প্রাথমিক বিদ্যালয়", lesson: 49 },
    { kanji: "～といいます", kana: "～といいます", bn: "একজনের নাম বলা", lesson: 49 },
    { kanji: "失礼いたします", kana: "しつれいいたします", bn: "বিদায় (しつれいします এর সম্মানজনক রূপ)", lesson: 49 },

    // Lesson 50 Data[span_24](start_span)[span_24](end_span)
    { kanji: "参ります", kana: "まいります", bn: "থাকা, আসা (いきます, きます এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "おります", kana: "おります", bn: "থাকা, আছেন (います এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "いただきます", kana: "いただきます", bn: "খাওয়া, পান করা, গ্রহণ করা (たべます, のみます, もらいます এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "申します", kana: "もうします", bn: "একজনের নাম বলা (いいます এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "致します", kana: "いたします", bn: "করা, খেলা (します এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "拝見します", kana: "はいけんします", bn: "দেখা (みます এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "存じます", kana: "ぞんじます", bn: "জানতে পারা (しります এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "伺います", kana: "うかがいます", bn: "জিজ্ঞাসা করা, শোনা, ভ্রমণ করা (ききます, いきます এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "お目にかかります", kana: "おめにかかります", bn: "দেখা করা (あいます এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "いれます [コーヒーを～]", kana: "いれます [コーヒーを～]", bn: "তৈরি করা [কফি]", lesson: 50 },
    { kanji: "用意します", kana: "よういします", bn: "প্রস্তুত করা, তৈরি করা", lesson: 50 },
    { kanji: "私", kana: "わたくし", bn: "আমি (わたし এর নম্র বা বিনীত রূপ)", lesson: 50 },
    { kanji: "ガイド", kana: "ガイド", bn: "পথপ্রদর্শক", lesson: 50 },
    { kanji: "メールアドレス", kana: "メールアドレス", bn: "ইমেইল ঠিকানা", lesson: 50 },
    { kanji: "スケジュール", kana: "スケジュール", bn: "সূচী বা তালিকা", lesson: 50 },
    { kanji: "さ来週", kana: "さらいしゅう", bn: "আগামী সপ্তাহের পরের সপ্তাহ", lesson: 50 },
    { kanji: "さ来月", kana: "さらいげつ", bn: "আগামী মাসের পরের মাস", lesson: 50 },
    { kanji: "さ来年", kana: "さらいねん", bn: "আগামী বছরের পরের বছর", lesson: 50 },
    { kanji: "初めに", kana: "はじめに", bn: "প্রথমে", lesson: 50 },
    { kanji: "緊張します", kana: "きんちょうします", bn: "উত্তেজনা হওয়া, নার্ভাস হওয়া", lesson: 50 },
    { kanji: "賞金", kana: "しょうきん", bn: "পুরস্কারের টাকা", lesson: 50 },
    { kanji: "きりん", kana: "きりん", bn: "জিরাফ", lesson: 50 },
    { kanji: "ころ", kana: "ころ", bn: "সময়, দিন", lesson: 50 },
    { kanji: "叶います [夢が～]", kana: "かないます [ゆめが～]", bn: "[স্বপ্ন] সত্যি হওয়া", lesson: 50 },
    { kanji: "応援します", kana: "おうえんします", bn: "সহযোগিতা করা", lesson: 50 },
    { kanji: "心から", kana: "こころから", bn: "হৃদয় থেকে, আন্তরিকভাবে", lesson: 50 },
    { kanji: "感謝します", kana: "かんしゃします", bn: "ধন্যবাদ, কৃতজ্ঞ হওয়া", lesson: 50 },
    { kanji: "お礼", kana: "おれい", bn: "কৃতজ্ঞতা, ধন্যবাদ", lesson: 50 },
    { kanji: "お元気で いらっしゃいますか。", kana: "おげんきで いらっしゃいますか。", bn: "আপনি কেমন আছেন? (おげんきですか এর সম্মানজনক রূপ)", lesson: 50 },
    { kanji: "迷惑を かけます", kana: "めいわくを かけます", bn: "সমস্যার কারণ, বিরক্তি, অসুবিধাজনক", lesson: 50 },
    { kanji: "生かします", kana: "いかします", bn: "ভালো ব্যবহার করা", lesson: 50 },
    { kanji: "ミュンヘン", kana: "ミュンヘン", bn: "মিউনিখ (জার্মানি)", lesson: 50 },
    { kanji: "郊外", kana: "こうがい", bn: "শহরতলি", lesson: 50 },
    { kanji: "アルバム", kana: "アルバム", bn: "এলবাম", lesson: 50 },
    { kanji: "最初", kana: "さいしょ", bn: "প্রথমত", lesson: 50 },
    { kanji: "最後", kana: "さいご", bn: "শেষে", lesson: 50 },
    { kanji: "ただいま", kana: "ただいま", bn: "আমি বাড়ি এসেছি", lesson: 50 },
    { kanji: "放送します", kana: "ほうそうします", bn: "সম্প্রচার করা", lesson: 50 },
    { kanji: "協力します", kana: "きょうりょくします", bn: "সহযোগিতা করা", lesson: 50 },
    { kanji: "迷惑", kana: "めいわく", bn: "সমস্যা", lesson: 50 },
    { kanji: "江戸東京博物館", kana: "えどとうきょうはくぶつかん", bn: "এদো টোকিও জাদুঘর", lesson: 50 }
];

// ==========================================
// 2. ISOLATED LOCAL STORAGE SYSTEM
// ==========================================
let allCardsDb = [];

function loadLocalDatabase() {
    const storageKey = 'n4_vocabulary_progress';
    const savedData = localStorage.getItem(storageKey); 
    let parsedData = savedData ? JSON.parse(savedData) : null;
    
    if (parsedData && parsedData.length === rawCards.length) {
        return parsedData;
    } else {
        const initialDb = rawCards.map((card, index) => ({
            id: index + 1,
            kanji: card.kanji,
            kana: card.kana,
            bn: card.bn,
            lesson: parseInt(card.lesson), 
            interval: 0,        
            ease: 2.5,          
            nextReview: 0 
        }));
        
        localStorage.setItem(storageKey, JSON.stringify(initialDb));
        return initialDb;
    }
}

function saveProgressLocally() {
    const storageKey = 'n4_vocabulary_progress';
    localStorage.setItem(storageKey, JSON.stringify(allCardsDb));
}

// ==========================================
// 3. APP STATE & UI LOGIC
// ==========================================
let reviewQueue = [];
let initialDeckSize = 0;
let isFlipped = false;
let totalSwipes = 0;
let correctSwipes = 0;

window.addEventListener('DOMContentLoaded', () => {
    allCardsDb = loadLocalDatabase();
    
    const lessonContainer = document.getElementById('lesson-buttons-container');
    
    // Generates buttons for Lessons 26 through 50
    for (let i = 26; i <= 50; i++) {
        const btn = document.createElement('button');
        btn.className = 'btn-lesson';
        btn.innerText = `Lesson ${i}`;
        btn.onclick = () => startSession(i);
        lessonContainer.appendChild(btn);
    }
});

// Intercepts phone swipe-back gesture
window.addEventListener('popstate', () => {
    goHomeLogic();
});

function showScreen(screenId) {
    document.getElementById('dashboard').classList.add('hidden');
    document.getElementById('study-screen').classList.add('hidden');
    document.getElementById('summary-screen').classList.add('hidden');
    document.getElementById(screenId).classList.remove('hidden');
}

function goHomeLogic() {
    showScreen('dashboard');
    document.getElementById('flashcard').classList.remove('flipped');
    document.getElementById('show-answer-btn').classList.remove('hidden');
    document.getElementById('rating-controls').classList.add('hidden');
    isFlipped = false;
}

function goHome() {
    history.back(); 
}

function startSession(lessonSelection) {
    history.pushState({ screen: 'study' }, '', '');
    
    const now = Date.now();
    
    if (lessonSelection === 'master') {
        reviewQueue = allCardsDb.filter(card => card.nextReview <= now);
        document.getElementById('study-title').innerText = "Master Deck";
    } else {
        reviewQueue = allCardsDb.filter(card => card.lesson === lessonSelection && card.nextReview <= now);
        document.getElementById('study-title').innerText = `Lesson ${lessonSelection}`;
    }

    if (reviewQueue.length === 0) {
        alert("No cards due right now! You are all caught up.");
        history.back();
        return;
    }

    reviewQueue = reviewQueue.sort(() => Math.random() - 0.5);
    initialDeckSize = reviewQueue.length;
    totalSwipes = 0;
    correctSwipes = 0;
    document.getElementById('progress-bar').style.width = '0%';

    showScreen('study-screen');
    loadNextCard();
}

function loadNextCard() {
    if (reviewQueue.length === 0) {
        finishSession();
        return;
    }

    const card = reviewQueue[0]; 
    const mode = document.getElementById('study-mode').value;
    
    if (mode === 'kanji') {
        document.getElementById('front-jp').innerText = card.kanji || card.kana;
        document.getElementById('back-kana').innerText = card.kana;
        document.getElementById('back-bn').innerText = card.bn;
    } else {
        document.getElementById('front-jp').innerText = card.kana;
        document.getElementById('back-kana').innerText = (card.kanji && card.kanji !== card.kana) ? `Kanji: ${card.kanji}` : "";
        document.getElementById('back-bn').innerText = card.bn;
    }

    document.getElementById('flashcard').classList.remove('flipped');
    
    setTimeout(() => {
        document.getElementById('show-answer-btn').classList.remove('hidden');
        document.getElementById('rating-controls').classList.add('hidden');
        isFlipped = false;
    }, 150);
}

function showAnswer() {
    if (isFlipped) return; 
    if (navigator.vibrate) navigator.vibrate(50);

    document.getElementById('flashcard').classList.add('flipped');
    document.getElementById('show-answer-btn').classList.add('hidden');
    document.getElementById('rating-controls').classList.remove('hidden');
    isFlipped = true;
}

function gradeCard(grade, event) {
    event.stopPropagation(); 
    if (navigator.vibrate) navigator.vibrate(20); 
    
    const currentCard = reviewQueue.shift(); 
    totalSwipes++; 

    if (grade === 'again') {
        currentCard.interval = 0;
        currentCard.nextReview = Date.now(); 
        reviewQueue.push(currentCard); 
    } else {
        correctSwipes++;
        
        if (currentCard.interval === 0) currentCard.interval = 1;
        else if (grade === 'hard') currentCard.interval *= 1.2;
        else if (grade === 'good') currentCard.interval *= currentCard.ease;
        else if (grade === 'easy') currentCard.interval *= (currentCard.ease * 1.3);

        currentCard.nextReview = Date.now() + (currentCard.interval * 24 * 60 * 60 * 1000);

        const completed = initialDeckSize - reviewQueue.length;
        const percentage = (completed / initialDeckSize) * 100;
        document.getElementById('progress-bar').style.width = `${percentage}%`;
    }

    const dbIndex = allCardsDb.findIndex(c => c.id === currentCard.id);
    if (dbIndex !== -1) {
        allCardsDb[dbIndex] = currentCard;
    }

    saveProgressLocally();
    loadNextCard();
}

function finishSession() {
    const accuracy = Math.round((correctSwipes / totalSwipes) * 100) || 0;
    
    document.getElementById('accuracy-display').innerText = `${accuracy}%`;
    document.getElementById('correct-count').innerText = correctSwipes;
    document.getElementById('total-count').innerText = totalSwipes;
    
    document.getElementById('accuracy-chart').style.background = `conic-gradient(#ffffff ${accuracy}%, rgba(255,255,255,0.2) 0%)`;

    showScreen('summary-screen');
    }
